nett-1.4.13a er klar for KS
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #127
Opened 2023-03-21 11:41 UTC by adilsofficial

2023-05-04 10:46 UTC, geirsf requested changes

2023-05-04 10:46 UTC, geirsf commented on Testreglar/1413/Nett/nett-1.4.13a.json
> +			"ht": "<p>Det ekstra innholdet skal forbli synlig helt til:</p>\n<ul>\n<li>du flytter musepekeren vekk</li>\n<li>du avviser innholdet eller</li>\n<li>informasjonen ikke lenger er gyldig</li>\n</ul
Spørsmålet er : _Forblir det ekstra innholdet synlig, helt til du flytter musepekeren vekk?_   men i første avsnitt står det: 
- du flytter musepekeren vekk
- du avviser innholdet eller
- informasjonen ikke lenger er gyldig

Alle tre punktene bør ikke være med her, dersom det ikke er meningen at alle 3 skal verifseres.

2023-05-04 10:46 UTC, geirsf commented on Testreglar/1413/Nett/nett-1.4.13a.json
> +			"ht": "<p>Det ekstra innholdet skal forbli synlig helt til:</p>\n<ul>\n<li>du flytter musepekeren vekk</li>\n<li>du avviser innholdet eller</li>\n<li>informasjonen ikke lenger er gyldig</li>\n</ul
_Hvis aktiveringen av elementet som viser det ekstra innholdet, også brukes til å lukke innholdet, skal det ikke føre til kontekstendring._   -> Hva er kilden til dette?

2023-05-04 10:46 UTC, geirsf commented on Testreglar/1413/Nett/nett-1.4.13a.json
> +					"utfall": "Det ekstra innholdet forstyrrer eller erstatter ikke annet innhold."
_Forstyrrer eller erstatter det ekstra innholdet, annet innhold?_

hva er det som gjør at vi får en ikke-forekomst når du svarer "nei" her? Finner ikke noe som tilsier at det gir unntak fra kravet?

2023-05-04 11:38 UTC, ABJORS approved these changes

2023-05-05 11:14 UTC, adilsofficial reviewed
Lagt inn kommentar og vil høre tilbakemelding fra @Sivzilla82 før ny commit.

2023-05-05 11:14 UTC, adilsofficial commented on Testreglar/1413/Nett/nett-1.4.13a.json
> +			"ht": "<p>Det ekstra innholdet skal forbli synlig helt til:</p>\n<ul>\n<li>du flytter musepekeren vekk</li>\n<li>du avviser innholdet eller</li>\n<li>informasjonen ikke lenger er gyldig</li>\n</ul
@Sivzilla82 Kan du svare denne kommentaren? Jeg husker ikke kilden.

2023-05-05 11:14 UTC, adilsofficial commented on Testreglar/1413/Nett/nett-1.4.13a.json
> +					"utfall": "Det ekstra innholdet forstyrrer eller erstatter ikke annet innhold."
Det står tydelig at **unntatt** der det ekstra innholdet formidler en inndatafeil eller det ikke forstyrrer eller erstatter annet innhold. @Sivzilla82 kan du også dobbeltsjekk her, dette gjelder første del av kravet "Mulig å avvise".

2023-05-08 08:33 UTC, Sivzilla82 commented on Testreglar/1413/Nett/nett-1.4.13a.json
> +					"utfall": "Det ekstra innholdet forstyrrer eller erstatter ikke annet innhold."
@adilsofficial  og @geirsf Det er unntak som står direkte i ordlyden i kravet i første punkt, mulig å avvise. 

"...unntatt der det ekstra innholdet formidler en inndatafeil eller det ikke forstyrrer eller erstatter annet innhold." Dersom det er tilfelle, er det ikkje krav til mekanisme.

2023-05-08 08:34 UTC, Sivzilla82 commented on Testreglar/1413/Nett/nett-1.4.13a.json
> +					"utfall": "Det ekstra innholdet forstyrrer eller erstatter ikke annet innhold."
Rg lurer på om me bør ha mulighet til å legge til ordlyden i kravet som ei kilde, på lik linje med teknikkar og failures m.m.

2023-05-22 10:46 UTC, geirsf requested changes

2023-05-22 12:07 UTC, adilsofficial commented on Testreglar/1413/Nett/nett-1.4.13a.json
> +					"type": "ikkjeForekomst",
Ja, det er ikke forekomst på kun først del av kravet, men resten av de to delene krav skal fortsatt sjekkes.

2023-05-22 12:07 UTC, adilsofficial commented on Testreglar/1413/Nett/nett-1.4.13a.json
> +					"type": "gaaTil",
Enig, fordi hvis det ikke finnes en mekanisme for å avvise det ekstra innholdet OG samtidig det forstyrrer eller erstatter det ekstra innholdet, annet innhold, så er det et brudd.

2023-05-23 07:56 UTC, adilsofficial commented on Testreglar/1413/Nett/nett-1.4.13a.json
> +	"kravTilSamsvar": "<p>Når innhold kommer til syne og så forsvinner ved at man holder musepekeren over innholdet og så flytter musepekeren vekk, gjelder alle de følgende punktene:</p>\r\n<ul>\r\n<li>
Det er en del av overordnede punkt, men vi bruker denne rutinene til å skrive unntaket for å gjør tekst litt mer lesbart.

2023-05-23 07:56 UTC, adilsofficial commented on Testreglar/1413/Nett/nett-1.4.13a.json
> +			"ht": "<p>Gå gjennom elementer med å holde musepekeren over dem, for å identifisere pekerfølsomt innhold (hover). Husk at du ikke skal trykke/klikke på elementene.</p>\n<p>Pekerfølsomt innhold er
Jeg tror ikke om det er nødvendig å skrive om det, når det står "musepekeren".

2023-05-23 07:56 UTC, adilsofficial commented on Testreglar/1413/Nett/nett-1.4.13a.json
> +			"ht": "<p>Slik tester du:</p>\n<ul>\n<li>Vis innholdet ved å holde musepekeren over elementet.</li>\n<li>Trykk på Esc eller en annen synlig, dokumentert snarvei oppgitt av innholdet, uten å flytte
Nei, det er ikke et krav.

2023-05-23 07:56 UTC, adilsofficial commented on Testreglar/1413/Nett/nett-1.4.13a.json
> +			"ht": "<p>Slik tester du:</p>\n<ul>\n<li>Vis det ekstra innholdet ved å holde musepekeren over elementet</li>\n<li>Sjekk om det ekstra innholdet forblir synlig i minst 60 sekunder, med mindre\n<ul
Faktisk den delen er fortsatt under diskusjon, basert på 2.2.1 Justerbar hastighet ville vi skrive 20 sekunder, men den er for lavt. Hva mener dere tidsavgrensningen? WCAG sier ingen ting om det per i dag.

2023-05-24 07:14 UTC, geirsf approved these changes

2023-05-26 09:10 UTC, merged