nett-1.4.13b er klar for KS
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #128
Opened 2023-03-21 11:43 UTC by adilsofficial

2023-05-04 11:21 UTC, geirsf requested changes

2023-05-04 11:21 UTC, geirsf commented on Testreglar/1413/Nett/nett-1.4.13b.json
> +					"utfall": "Det ekstra innholdet forstyrrer eller erstatter ikke annet innhold."
Som i nett 1.4.13.a Forstår ikke helt hva som trigger ikke-forekomst her.

2023-05-04 11:47 UTC, ABJORS requested changes

2023-05-04 11:47 UTC, ABJORS commented on Testreglar/1413/Nett/nett-1.4.13b.json
> +			"ht": "<p>Tab gjennom elementer med tastaturet for å identifisere ekstra innhold som viser ved tastaturfokus.</p>\n<p>Dette er innhold der ekstra innhold kommer til syne og så forsvinner, når innh
1. Skriv om setning? Veldig mange "innhold": "Dette er innhold der ekstra innhold kommer til syne og så forsvinner, når innholdet får tastaturfokus og deretter flytter tastaturfokus vekk." Forslag til to første setninger: " Tab gjennom elementer med tastaturet for å identifisere ekstra innhold som vises ved tastaturfokus. Dette er ekstra innhold som kommer til syne når elementet får tastaturfokus, og deretter forsvinner når tastaturfokus flyttes vekk"
2. Skriv om: "skal også kunne betjenes ved kun med..." forslag: "skal også kunne betjenes med tastaturet"

2023-05-23 08:06 UTC, adilsofficial commented on Testreglar/1413/Nett/nett-1.4.13b.json
> +	"kravTilSamsvar": "<p>Når innhold kommer til syne og så forsvinner ved at man flytter tastaturfokus til innholdet og deretter flytter fokus vekk, gjelder alle de følgende punktene:</p>\r\n<ul>\r\n<l
Det er litt krevende å dekke alle mulig sitasjoner med testregler, når WCAG retningslinjer er såpass generelle. Hvis ekstra innhold vises ved tastaturfokus og ikke forsvinner når tastaturfokus flyttes vekk, kan det være mulig at det er bruk en onfocus for å åpne en dialogboks/modellvindu isf. hover innhold?

2023-05-23 08:06 UTC, adilsofficial commented on Testreglar/1413/Nett/nett-1.4.13b.json
> +	"kravTilSamsvar": "<p>Når innhold kommer til syne og så forsvinner ved at man flytter tastaturfokus til innholdet og deretter flytter fokus vekk, gjelder alle de følgende punktene:</p>\r\n<ul>\r\n<l
Nei

2023-05-23 08:06 UTC, adilsofficial commented on Testreglar/1413/Nett/nett-1.4.13b.json
> +			"spm": "Finnes det pekerfølsomt innhold som kommer til syne ved tastaturfokus (fokus) på testsiden?",
Godt poeng, vi har diskutert dette, men det ekstra innhold som vises ved tastaturfokus i konteksten av 1.4.13 er pekerfølsomt innhold i teori. Jeg tror begrepet gir meningen, men kjenner du et annet begrep?

2023-05-23 08:06 UTC, adilsofficial commented on Testreglar/1413/Nett/nett-1.4.13b.json
> +					"utfall": "Testsiden har ikke pekerfølsomt innhold."
@Sivzilla82 kan du svare denne kommentaren?

2023-05-23 08:06 UTC, adilsofficial commented on Testreglar/1413/Nett/nett-1.4.13b.json
> +			"ht": "<p>Slik tester du:</p>\n<ul>\n<li>Vis innholdet ved å navigere med tastatur til elementet.</li>\n<li>Trykk på Esc eller en annen synlig, dokumentert snarvei oppgitt av innholdet, uten å fly
Nei.

2023-05-23 08:06 UTC, adilsofficial commented on Testreglar/1413/Nett/nett-1.4.13b.json
> +			"ht": "<p>Slik tester du:</p>\n<ul>\n<li>Vis det ekstra innholdet ved å holde fokus på elementet</li>\n<li>Sjekk om det ekstra innholdet forblir synlig i minst 60 sekunder, med mindre\n<ul>\n<li>d
Har svart kommentaren i nett-1.4.13a.

2023-05-23 08:45 UTC, Sivzilla82 commented on Testreglar/1413/Nett/nett-1.4.13b.json
> +					"utfall": "Testsiden har ikke pekerfølsomt innhold."
@adilsofficial @annethyme Vi kan gjerne bruke "Innhold ved tastaturfokus", når vi tester tastatur. Det er dette som står i SK.

2023-05-25 06:30 UTC, ABJORS approved these changes

2023-05-26 11:15 UTC, geirsf requested changes

2023-05-26 11:15 UTC, geirsf commented on Testreglar/1413/Nett/nett-1.4.13b.json
> +					"type": "ikkjeForekomst",
Som i 1.4.13a- Dette er ikke en ikke forekomst, du må gå videre å **sjekke synlighet.**

2023-05-26 11:15 UTC, geirsf commented on Testreglar/1413/Nett/nett-1.4.13b.json
> +				"ja": {
Ja her gir **BRUDD** ( Det er ikke mulig å avise og lukke og ingen unntak gjelder)

2023-05-26 11:15 UTC, geirsf commented on Testreglar/1413/Nett/nett-1.4.13b.json
> +					"utfall": "Det ekstra innholdet kan ikke betjenes, fordi det ikke er mulig å avvise eller lukke det ekstra innholdet."
Nei her betyr at du må videre å sjekke synlighet. (3.6)

2023-06-06 11:48 UTC, geirsf commented on Testreglar/1413/Nett/nett-1.4.13b.json
> +	"kravTilSamsvar": "<p>Når innhold kommer til syne og så forsvinner ved at man flytter tastaturfokus til innholdet og deretter flytter fokus vekk, gjelder alle de følgende punktene:</p>\r\n<ul>\r\n<l
Innholdet må forsvinne for at kravet skal gjelde ( keyboard focus triggers additional content to become visible **and then hidden**)

2023-06-06 13:24 UTC, merged