app-2.5.2a er klar for KS
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #139
Opened 2023-05-23 11:38 UTC by adilsofficial

2023-06-09 11:40 UTC, geirsf requested changes

2023-06-09 11:40 UTC, geirsf commented on Testreglar/252/App/app-2.5.2a.json
> +			"ht": "<p>Oppgi appside-ID</p>",
Oppdater til standard app tekst

2023-06-09 11:40 UTC, geirsf commented on Testreglar/252/App/app-2.5.2a.json
> +					"utfall": "Trykkhandlingen (down-event) utløser ikke funksjonen"
```suggestion
					"utfall": "Trykkhandlingen (down-event) utløser ikke funksjonen."
```

2023-06-09 11:40 UTC, geirsf commented on Testreglar/252/App/app-2.5.2a.json
> +					"utfall": "Slipphandlingen (up-event) opphever ikke resultatet av den foregående trykkhandlingen (down-event)"
```suggestion
					"utfall": "Slipphandlingen (up-event) opphever ikke resultatet av den foregående trykkhandlingen (down-event)."
```

2023-06-09 11:40 UTC, geirsf commented on Testreglar/252/App/app-2.5.2a.json
> +					"utfall": "Slipphandlingen (up-event) opphever resultatet av den foregående trykkhandlingen (down-event)"
```suggestion
					"utfall": "Slipphandlingen (up-event) opphever resultatet av den foregående trykkhandlingen (down-event)."
```

2023-06-09 11:40 UTC, geirsf commented on Testreglar/252/App/app-2.5.2a.json
> +			"ht": "<p>Slik tester du:</p>\n<ul>\n<li>Trykk og hold nede pekeren du bruker (museknappen, fingeren eller stylus) på innholdet på berøringsskjermen</li>\n<li>Sjekk om trykkhandlingen (down-event)
Museknappen er vell ikke så relevant for app?

2023-06-09 11:40 UTC, geirsf commented on Testreglar/252/App/app-2.5.2a.json
> +					"utfall": "Det er avgjørende å utføre funksjonen på trykkhandlingen (down-event)."
Slik kravet til samsvar er bygget opp er "Det er avgjørende å utføre funksjonen på trykkhandlingen (down-event)" en måte å oppfylle kravet på. (Altså samsvar og ikke ikke-forekomst).

2023-06-09 11:40 UTC, geirsf commented on Testreglar/252/App/app-2.5.2a.json
> +					"type": "gaaTil",
ja her er vell **samsvar**? ref punkt 3 i krav til samsvar: Slipphandlingen (up-event) opphever resultatet av den foregående trykkhandlingen (down-event)

2023-06-09 11:40 UTC, geirsf commented on Testreglar/252/App/app-2.5.2a.json
> +					"utfall": "Slipphandlingen (up-event) opphever ikke resultatet av den foregående trykkhandlingen (down-event)"
På nei skal du vell sjekke mekanisme ref punkt 2 i krav til samsvar: _Funksjonen utføres på slipphandlingen (up-event), og det finnes en mekanisme
- for å avbryte funksjonen før den utføres, eller
- for å angre funksjonen etter at den er utført eller_

2023-06-15 14:08 UTC, geirsf approved these changes

2023-06-15 14:10 UTC, ABJORS approved these changes

2023-06-15 14:10 UTC, merged