app-2.5.4a er klar for KS
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #140
Opened 2023-05-23 12:50 UTC by adilsofficial

2023-05-25 09:58 UTC, ABJORS approved these changes

2023-06-09 11:16 UTC, geirsf requested changes

2023-06-09 11:16 UTC, geirsf commented on Testreglar/254/App/app-2.5.4a.json
> +			"spm": "Har virksomheten svart at appen har funksjonalitet som kan betjenes med bevegelsesaktivering?",
Som i nett-2.5.4  #138 -> Spørsmålene må være generelle og ikke knyttet opp mot vår tilsynsprosess.

2023-06-09 11:16 UTC, geirsf commented on Testreglar/254/App/app-2.5.4a.json
> +			"ht": "<p>Bruk informasjonen fra virksomheten. Beskriv funksjonaliteten, slik at det er mulig å identifisere den i ettertid. Hvis det gjelder flere funksjoner, registrerer du en og en.</p>",
Samme som kommentar over

2023-06-09 11:16 UTC, geirsf commented on Testreglar/254/App/app-2.5.4a.json
> +			"spm": "Hvilken appside tester du?",
Bytt til korrekt tekst (Se mal for standardtekster.)

2023-06-16 08:34 UTC, merged