nett-4.1.3a er under arbeid
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #141
Opened 2023-05-25 12:26 UTC by adilsofficial

2023-06-09 11:47 UTC, geirsf requested changes

2023-06-09 11:47 UTC, geirsf commented on Testreglar/413/Nett/nett-4.1.3a.json
> +	"kravTilSamsvar": "<ul>\r\n<li>Det blir gitt en statusbeskjed som ikke får fokus og</li>\r\n<li>Statusbeskjeden gir brukeren informasjon om én av følgende forhold:\r\n<ul>\r\n<li>Vellykketheten elle
Her mangler det info om at når / hvilket innholdet kravet gjelder (applicability)

2023-06-09 11:47 UTC, geirsf commented on Testreglar/413/Nett/nett-4.1.3a.json
> +					"utfall": "Statusbeksjed er ikke programmatisk bestemt med hverken <code>role=\"status\"</code> eller <code>aria-live=\"polite\"</code>"
Utfall skal ikke ha HTML kode i seg (Dette vil skape problem i feks PowerBi)

2023-06-15 15:55 UTC, adilsofficial commented on Testreglar/413/Nett/nett-4.1.3a.json
> +					"utfall": "Statusbeksjed er ikke programmatisk bestemt med hverken <code>role=\"status\"</code> eller <code>aria-live=\"polite\"</code>"
Fikset

2023-07-07 08:50 UTC, ABJORS approved these changes

2023-07-11 12:27 UTC, merged