app-1.2.5a er klar for KS
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #148
Opened 2023-06-14 06:48 UTC by adilsofficial

2023-06-15 09:45 UTC, geirsf requested changes
Justeres etter endringene vi ble ening om på møte.

2023-06-16 06:28 UTC, geirsf requested changes

2023-06-16 06:28 UTC, geirsf commented on Testreglar/125/App/app-1.2.5a.json
> +			"ht": "<p>Hva som er «viktig» visuell informasjon vil variere etter type video, og blir avgjort etter en totalvurdering. Eksempler på visuell informasjon som vanligvis skal synstolkes er ifølge me
Det bør legges til egne steg for å ivareta G203. I tillegg bør det presiseres hva som er ok med hensyn til at videoen må pauses for å få med seg synstolkingen.

2023-06-16 11:49 UTC, geirsf approved these changes

2023-06-16 11:50 UTC, ABJORS approved these changes

2023-06-16 11:51 UTC, merged