Lagt inn nye standardtekster
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #150
Opened 2023-06-15 14:03 UTC by adilsofficial

2023-06-15 14:15 UTC, ABJORS approved these changes

2023-06-16 06:16 UTC, geirsf requested changes

2023-06-16 06:16 UTC, geirsf commented on Mal/standardtekstar.json
> +            "nn": "Beskriv elementa, slik at det er mogleg å identifisere det i ettertid. Viss det gjeld fleire element, registrerer du eit og eit.",
```suggestion
            "nn": "Beskriv elementet, slik at det er mogleg å identifisere det i ettertid. Viss det gjeld fleire element, registrerer du eit og eit.",
```

2023-06-16 06:16 UTC, geirsf commented on Mal/standardtekstar.json
> +            "nn": "Beskriv elementa, slik at det er mogleg å identifisere det i ettertid. Viss det gjeld fleire element, registrerer du eit og eit.",
```suggestion
            "nn": "Beskriv elementet, slik at det er mogleg å identifisere det i ettertid. Viss det gjeld fleire element, registrerer du eit og eit.",
```

2023-06-16 08:41 UTC, merged