Standardtekst til spørsmål og hjelpetekst for skjermleser i app testregler
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #197
Opened 2023-09-06 12:03 UTC by adilsofficial

2023-09-06 12:21 UTC, geirsf requested changes

2023-09-06 12:21 UTC, geirsf commented on Mal/standardtekstar.json
> +            "bm": "Slik tester du:\n<ul>\n<li>Aktiver skjermleser (opplesningsfunksjon)\n<ul>\n<li>iOS: VoiceOver</li>\n<li>Android: Talkback</li>\n</ul>\n</li>\n<li>Åpne appsiden du tester</li>\n<li
Skrivefeil: "et av skjemaelementer"  mener du minst et "skjemaelement" ?

2023-09-06 12:21 UTC, geirsf commented on Mal/standardtekstar.json
> +            "bm": "Slik tester du:\n<ul>\n<li>Aktiver skjermleser (opplesningsfunksjon)\n<ul>\n<li>iOS: VoiceOver</li>\n<li>Android: Talkback</li>\n</ul>\n</li>\n<li>Åpne appsiden du tester</li>\n<li
Skrivefeil: "i det skjemaet" mener du "i skjemaet" ?

2023-09-11 12:01 UTC, geirsf requested changes

2023-09-11 12:01 UTC, geirsf commented on Mal/standardtekstar.json
> +            "nn":"Er det mogleg å sveipe til skjemaelementer?",
"elementer" er ikke lov på nynorsk: https://ordbokene.no/nn/search?0=e&1=l&2=e&3=m&4=e&5=n&6=t&7=e&8=r&q=element       . Dersom det skal være bunden form fleirtal skal det brukes "elementa" og dersom det er ubunden fleirtall skal det være "element".

2023-09-13 08:03 UTC, ABJORS approved these changes

2023-09-13 10:25 UTC, geirsf approved these changes

2023-09-15 06:47 UTC, merged