app 1.4.4a JBK klar til ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #231
Opened 2023-10-24 07:59 UTC by janBeniaminKwiek

2023-10-24 13:48 UTC, geirsf requested changes

2023-10-24 13:48 UTC, geirsf commented on Testreglar/1.4.4/App/app-144a.json
> +					"utfall": "Tekst på appsida kan forstørrast til minst 200 %, utan tap av innhald eller funksjonalitet"
```suggestion
					"utfall": "Tekst på appsida kan forstørrast til minst 200 %, utan tap av innhald eller funksjonalitet."
```

2023-10-24 13:48 UTC, geirsf commented on Testreglar/1.4.4/App/app-144a.json
> +					"utfall": "Tekst på appsida blir ikkje forstørra til minst 200 %, utan tap av innhald eller funksjonalitet"
```suggestion
					"utfall": "Tekst på appsida blir ikkje forstørra til minst 200 %, utan tap av innhald eller funksjonalitet."
```

2023-10-24 13:48 UTC, geirsf commented on Testreglar/1.4.4/App/app-144a.json
> +			"label": "",
Manglar label

2023-10-24 13:48 UTC, geirsf commented on Testreglar/1.4.4/App/app-144a.json
> +	"kravTilSamsvar": "<p><span style=\"font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;\"><span style=\"mso-list: Ignore;\"><span style=\"font: 7.0pt 'Times New Roman
```suggestion
	"kravTilSamsvar": "<p>All tekst kan forstørres opp til minst 200 % visning uten at innhold eller funksjonalitet går tapt.</p>",
```

2023-10-24 13:48 UTC, geirsf commented on Testreglar/1.4.4/App/app-144a.json
> +					"utfall": "Appsida har ikkje tekst"
```suggestion
					"utfall": "Appsida har ikkje tekst."
```

2023-10-24 13:48 UTC, geirsf commented on Testreglar/1.4.4/App/app-144a.json
> +			"label": "",
Bør være multilinje

2023-10-27 10:51 UTC, janBeniaminKwiek reviewed
Endringer rettet

2023-10-27 10:51 UTC, janBeniaminKwiek commented on Testreglar/1.4.4/App/app-144a.json
> +			"label": "",
Rettet,

2023-11-02 14:05 UTC, ABJORS commented on Testreglar/1.4.4/App/app-144a.json
> +			"spm": "Har appsida same tekstleg innhald og funksjonalitet i 200 % visning, som i 100 % visning?",
tekstlege?

2023-11-23 12:02 UTC, geirsf approved these changes

2023-12-06 09:32 UTC, janBeniaminKwiek commented on Testreglar/1.4.4/App/app-144a.json
> +			"spm": "Har appsida same tekstleg innhald og funksjonalitet i 200 % visning, som i 100 % visning?",
ok

2023-12-06 15:08 UTC, ABJORS approved these changes

2023-12-11 07:52 UTC, merged