Nett-2.1.1a-jbk-Det-er-mogleg-å-nå-innhald-og-bruke-funksjonalitet-med-tastatur-2023  Klar for KS
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #234
Opened 2023-10-27 12:35 UTC by janBeniaminKwiek

2023-11-09 15:26 UTC, ABJORS requested changes

2023-11-23 12:13 UTC, geirsf requested changes

2023-12-06 14:25 UTC, geirsf requested changes

2023-12-06 14:25 UTC, geirsf commented on Testreglar/2.1.1/Nett/nett-2.1.1a.json
> +					"utfall": "Det er mogleg å nå og betene all funksjonalitet på nettsida via dokumentert, alternativ tastaturnavigasjon."
Du kan vell ikke garantere at du kan **nå og betene all funksjonalitet på nettsida** på dette steget.  Dersom du har to element du ikke når med tastaturet og bare én av det har et alternativ vil dette utfallet bli feil. Må heller være feks "Innhold det er mogleg å nå og betene via dokumentert, alternativ tastaturnavigasjon."

2023-12-06 14:25 UTC, geirsf commented on Testreglar/2.1.1/Nett/nett-2.1.1a.json
> +					"utfall": "Det er ikkje mogleg å nå og betene alt innhald/funksjonalitet på nettsida med tastatur."
```suggestion
					"utfall": "Innhald/funksjonalitet det ikkje er mogleg å nå og betene med tastatur."
```

2023-12-06 14:25 UTC, geirsf commented on Testreglar/2.1.1/Nett/nett-2.1.1a.json
> +					"utfall": "Det er mogleg å nå og betene all funksjonalitet på nettsida via dokumentert, alternativ tastaturnavigasjon."
```suggestion
					"utfall": "Innhald/funksjonalitet det er mogleg å nå og betene via dokumentert, alternativ tastaturnavigasjon."
```

2023-12-06 14:25 UTC, geirsf commented on Testreglar/2.1.1/Nett/nett-2.1.1a.json
> +					"utfall": "Innhald på nettsida som ikkje er føremålsteneleg å betene med tastatur."
```suggestion
					"utfall": "Innhald/funksjonalitet på nettsida som ikkje er føremålsteneleg å betene med tastatur."
```

2023-12-06 14:26 UTC, Sivzilla82 approved these changes

2023-12-06 14:31 UTC, geirsf approved these changes

2023-12-11 07:53 UTC, merged