Nett-2.4.7a Innhald som kan brukast med tastatur, får synleg fokusmarkering 2023 klar for KS.
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #235
Opened 2023-10-27 13:05 UTC by janBeniaminKwiek

2023-11-09 15:35 UTC, ABJORS requested changes

2023-11-09 15:35 UTC, ABJORS commented on Testreglar/2.4.7/Nett/nett-2.4.7a-jbk.json
> +					"utfall": "Nettside der alle element det er mogleg å bruke med tastaturet, får synleg fokusmarkering."
Samsvar spørsmål/utfall: Forslag "Alle element som er mogleg å bruke med tastatur, får synlig fokusmarkering"

2023-11-09 15:35 UTC, ABJORS commented on Testreglar/2.4.7/Nett/nett-2.4.7a-jbk.json
> +				}
Samsvar spørsmål/utfall: Forslag "Element som er mogleg å bruke med tastatur, får ikkje synlig fokusmarkering"

2023-12-05 07:46 UTC, Sivzilla82 commented on Testreglar/2.4.7/Nett/nett-2.4.7a-jbk.json
> +				}
Endra

2023-12-05 07:46 UTC, Sivzilla82 commented on Testreglar/2.4.7/Nett/nett-2.4.7a-jbk.json
> +					"utfall": "Nettside der alle element det er mogleg å bruke med tastaturet, får synleg fokusmarkering."
Endra

2023-12-06 07:22 UTC, geirsf requested changes

2023-12-06 15:03 UTC, ABJORS approved these changes

2023-12-07 07:14 UTC, geirsf approved these changes

2023-12-11 07:54 UTC, merged