Nett-2.1.2a Det finst ingen tastaturfelle på nettsida 2023 klar for KS.
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #240
Opened 2023-11-02 11:40 UTC by janBeniaminKwiek

2023-11-08 07:20 UTC, geirsf requested changes

2023-11-08 07:20 UTC, geirsf commented on Testreglar/2.1.2/Nett/nett-2.1.2.json
> +	"kravTilSamsvar": "<p class=\"MsoNormal\" style=\"margin-bottom: 6.0pt; margin-top: 0in; mso-margin-bottom-alt: 8.0pt; mso-margin-top-alt: 0in; mso-add-space: auto;\"><span style=\"font-family: 'Ari
```suggestion
	"kravTilSamsvar": "<p>Det er mulig å navigere gjennom alt innhold på nettsiden som kan få tastaturfokus, uten å bli stående fast i et element.</p>\r\n<ul type=\"disc\">\r\n<li>Alternativ tastaturnavigasjon er beskrevet for brukeren, dersom standardmetoder ikke er brukt.</li>\r\n</ul>",
```

2023-11-08 07:20 UTC, geirsf commented on Testreglar/2.1.2/Nett/nett-2.1.2.json
> +			"ht": "<p>Bruk standard tastaturnavigasjon for å navigere på nettsida. </p>\n<ul>\n<li>For å betene innhaldet kan du også bruke enter, mellom og pil.</li>\n<li>For å rygge med tastaturet, bruk Shi
Det bør gå fram i hjelpeteksten kva som er ei "tastaturfelle".

2023-11-09 15:49 UTC, ABJORS requested changes

2023-11-09 15:49 UTC, ABJORS commented on Testreglar/2.1.2/Nett/nett-2.1.2.json
> +	"kravTilSamsvar": "<p class=\"MsoNormal\" style=\"margin-bottom: 6.0pt; margin-top: 0in; mso-margin-bottom-alt: 8.0pt; mso-margin-top-alt: 0in; mso-add-space: auto;\"><span style=\"font-family: 'Ari
bytte ut "i element" med "på element"?. Eventuelt droppe "i et element". Altså: "Det er mulig å navigere gjennom alt innhold på nettsiden som kan få tastaturfokus, uten å bli stående fast"

2023-11-09 15:49 UTC, ABJORS commented on Testreglar/2.1.2/Nett/nett-2.1.2.json
> +					"utfall": "Testsida har ikkje innhald/funksjonalitet som er mogleg å nå/betene med tastatur."
samsvar spørsmål/utfall: " Det finst ikkje element på nettsida som det er mogleg å navigere til med tastaturet"

2023-11-09 15:49 UTC, ABJORS commented on Testreglar/2.1.2/Nett/nett-2.1.2.json
> +			"spm": "Får du indikasjon på at det finst minst ei tastaturfelle på nettsida?",
Er vi sikker på at vi mener indikasjon? vet man eller vet man ikke at det er tastaturfelle på sida etter at dette steget er gjennomført?

2023-11-09 15:49 UTC, ABJORS commented on Testreglar/2.1.2/Nett/nett-2.1.2.json
> +					"utfall": "Testsida har ikkje tastaturfelle."
samsvar spørsmål utfall: her tror jeg kanskje spørsmålet må endres. Spør om det er indikasjon, men utfallet sier at det ikke er.

2023-11-09 15:49 UTC, ABJORS commented on Testreglar/2.1.2/Nett/nett-2.1.2.json
> +					"utfall": "Alternativ tastaturnavigasjon er ikkje beskrive for brukaren."
Foreslår å justere både spørsmål og utfall. Forslag spm: "Er det beskrive ein alternativ tastaturnavigasjon, i nærleiken av elementet?", utfall: "Det er ikke beskrive ein alternativ tastaturnavigasjon i nærleiken av elementet"

2023-12-07 12:42 UTC, geirsf requested changes

2023-12-08 08:33 UTC, geirsf approved these changes

2023-12-11 07:55 UTC, adilsofficial commented on Testreglar/2.1.2/Nett/nett-2.1.2.json
> +	"namn": "nett-2.1.2a Det finst ingen tastaturfeller på nettsida 2023",
```suggestion
	"namn": "Nett-2.1.2a Det finst ingen tastaturfeller på nettsida 2023",
```

2023-12-11 07:56 UTC, merged