app-2.1.2a Det finst ingen tastaturfelle på nettsida 2023 klar for KS
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #241
Opened 2023-11-02 14:34 UTC by janBeniaminKwiek

2023-11-08 07:28 UTC, geirsf requested changes

2023-11-08 07:28 UTC, geirsf commented on Testreglar/2.1.2/App/app-2.1.2a.json
> +	"kravTilSamsvar": "<p class=\"MsoNormal\" style=\"margin-bottom: 6.0pt; margin-top: 0in; mso-margin-bottom-alt: 8.0pt; mso-margin-top-alt: 0in; mso-add-space: auto;\"><span style=\"font-family: 'Ari
```suggestion
	"kravTilSamsvar": "<p>Det er mulig å navigere gjennom alt innhold i appen som kan få tastaturfokus, uten å bli stående fast i et element.</p>",
```

2023-11-08 07:28 UTC, geirsf commented on Testreglar/2.1.2/App/app-2.1.2a.json
> +			"ht": "<p>Sveip sakte for å navigere på appsida. </p>\n<ul>\n<li>Kontroller at du sveipar gjennom alt innhald og at du kjem tilbake til start.</li>\n<li>Hugs å opne menyar, modaler, og å gå inn i
"Sveipfelle" må forklares i hjelpeteksten.

2023-11-08 07:28 UTC, geirsf commented on Testreglar/2.1.2/App/app-2.1.2a.json
> +			"ht": "<p><strong>Merk:</strong> Bruk av tilbake-knappen på enheten er ikkje ein godkjent måte å oppfylle kravet på.</p>",
Har vi en kilde?   Feks G21

2023-11-09 15:54 UTC, ABJORS requested changes

2023-11-09 15:54 UTC, ABJORS commented on Testreglar/2.1.2/App/app-2.1.2a.json
> +					"utfall": "Appsida har ikkje innhald/funksjonalitet som er mogleg å nå/betene med sveiping."
samsvar spørsmål/utfall. Forslag: "Det finst ikkje element det er mogleg å sveipe til på appsida"

2023-11-09 15:54 UTC, ABJORS commented on Testreglar/2.1.2/App/app-2.1.2a.json
> +			"spm": "Får du indikasjon på at det finst minst ei sveipefelle på appsida?",
Usikker på bruken av "Indikasjon" her. Her gjennomføres det vel en test om det finnes sveipefeller? da bør det framgå av spørsmålet. Eventuelt bør utfallet endres. Feks: " Det er ikkje indikasjon på sveipefelle på appsida"

2023-12-04 10:38 UTC, geirsf commented
Kommentarer må resolves før denne kan sendes tilbake til kvalitetssikring.

2023-12-06 15:05 UTC, ABJORS approved these changes

2023-12-06 19:28 UTC, janBeniaminKwiek commented on Testreglar/2.1.2/App/app-2.1.2a.json
> +	"kravTilSamsvar": "<p class=\"MsoNormal\" style=\"margin-bottom: 6.0pt; margin-top: 0in; mso-margin-bottom-alt: 8.0pt; mso-margin-top-alt: 0in; mso-add-space: auto;\"><span style=\"font-family: 'Ari
ok

2023-12-06 19:29 UTC, janBeniaminKwiek commented on Testreglar/2.1.2/App/app-2.1.2a.json
> +			"ht": "<p>Sveip sakte for å navigere på appsida. </p>\n<ul>\n<li>Kontroller at du sveipar gjennom alt innhald og at du kjem tilbake til start.</li>\n<li>Hugs å opne menyar, modaler, og å gå inn i
ok.

2023-12-06 19:29 UTC, janBeniaminKwiek commented on Testreglar/2.1.2/App/app-2.1.2a.json
> +			"spm": "Får du indikasjon på at det finst minst ei sveipefelle på appsida?",
ok.

2023-12-08 11:00 UTC, geirsf commented on Testreglar/2.1.2/App/app-2.1.2a.json
> +			"label": "Skjermbilde:",
```suggestion
			"label": "Appside:",
```

2023-12-08 11:01 UTC, geirsf commented on Testreglar/2.1.2/App/app-2.1.2a.json
> +					"utfall": "Appsida har ikkje sveipefeller."
```suggestion
					"utfall": "Elementet har ikkje sveipefelle."
```

2023-12-08 11:03 UTC, geirsf commented on Testreglar/2.1.2/App/app-2.1.2a.json
> +					"utfall": "Appsida har sveipefeller."
```suggestion
					"utfall": "Element med sveipefelle."
```

2023-12-11 07:57 UTC, adilsofficial commented on Testreglar/2.1.2/App/app-2.1.2a.json
> +	"namn": "app-2.1.2a Det finst ingen sveipefeller på appsida 2023",
```suggestion
	"namn": "App-2.1.2a Det finst ingen sveipefeller på appsida 2023",
```

2023-12-11 07:58 UTC, merged