nett 1.1.1b er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #277
Opened 2023-12-04 14:45 UTC by adilsofficial

2023-12-06 15:37 UTC, ABJORS approved these changes

2023-12-11 09:00 UTC, janBeniaminKwiek requested changes

2023-12-11 09:00 UTC, janBeniaminKwiek commented on Testreglar/1.1.1/Nett/nett-1.1.1b.json
> +			"ht": "<p>Gjør em skjønnsmessig vurdering av om innholdet i det tilgjengelige navnet, gir tilstrekkelig informasjon om hva som er lenkemålet. Lenkemålet er dit brukeren kommer ved å aktivere lenke
Hva om lenken går til nedlasting av FilXyz.pdf og navnet er last ned Filxyz.pdf?

2023-12-13 09:47 UTC, geirsf requested changes

2023-12-13 09:47 UTC, geirsf commented on Testreglar/1.1.1/Nett/nett-1.1.1b.json
> +			"ht": "<p>Slik finner du lenkede bilder:</p>\n<ul>\n<li>Før musepekeren over bilder på nettsiden og se om markøren viser at bilder er klikkbare (hånd) eller</li>\n<li>Bruke Inspiser i nettleseren
Det er vell bare et forslag (av flere), og deaktivering av visning av interaktive element er vell noe du må gå inn å aktiver, er vell ingen nettlesere som har det deaktivert (på desktop) som standard=?

2023-12-13 09:47 UTC, geirsf commented on Testreglar/1.1.1/Nett/nett-1.1.1b.json
> +			"spm": "Har det lenkede bildet et tekstalternativ (tilgjengelig navn)?",
```suggestion
			"spm": "Har det lenkede bildet et tilgjengelig navn?",
```

2023-12-13 09:47 UTC, geirsf commented on Testreglar/1.1.1/Nett/nett-1.1.1b.json
> +			"spm": "Har det lenkede bildet et tekstalternativ (tilgjengelig navn)?",
Kan lenkede bilder ha **tekstalternativ** som ikke er lenken som bilde ligger inni sitt **tilgjengelig navn**?

2023-12-13 09:47 UTC, geirsf commented on Testreglar/1.1.1/Nett/nett-1.1.1b.json
> +			"ht": "<p>Du skal åpne lenken for å finne informasjon om lenkemålet. Denne skal du senere bruke for å vurdere om tilgjengelig navn er tilstrekkelig.</p>",
Kanskje tipse om åpne url-en i ny fane?  Da slipper du å miste testelementet.

2023-12-19 10:12 UTC, adilsofficial commented on Testreglar/1.1.1/Nett/nett-1.1.1b.json
> +			"ht": "<p>Gjør em skjønnsmessig vurdering av om innholdet i det tilgjengelige navnet, gir tilstrekkelig informasjon om hva som er lenkemålet. Lenkemålet er dit brukeren kommer ved å aktivere lenke
Fjernet denne merknaden.

2023-12-19 13:54 UTC, geirsf approved these changes

2023-12-19 13:54 UTC, geirsf commented on Testreglar/1.1.1/Nett/nett-1.1.1b.json
> +			"spm": "Hvilket tekstalternativ tester du?",
```suggestion
			"spm": "Hva er det lenkede bildet sitt tilgjengelig navn?",
```

2023-12-19 13:54 UTC, geirsf commented on Testreglar/1.1.1/Nett/nett-1.1.1b.json
> +			"spm": "Hvilket tekstalternativ tester du?",
Ref at ledeteksten bare snakker om tilgjengelige navn

2024-01-08 11:35 UTC, janBeniaminKwiek approved these changes

2024-01-10 08:55 UTC, merged