nett 1.1.1c er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #278
Opened 2023-12-04 14:52 UTC by adilsofficial

2023-12-11 09:14 UTC, janBeniaminKwiek requested changes

2023-12-11 09:14 UTC, janBeniaminKwiek commented on Testreglar/1.1.1/Nett/nett-1.1.1c.json
> +			"ht": "<p>Slik tester du</p>\n<ul>\n<li>Gå tilbake til testsiden</li>\n<li>Inspiser det klikkbare området, <code>&lt;area&gt;</code>-elementet, du registrerte i forrige steg.</li>\n<li>Under Compu
Hva tenkes med accessibility checker?

2023-12-11 09:14 UTC, janBeniaminKwiek commented on Testreglar/1.1.1/Nett/nett-1.1.1c.json
> +			"ht": "<p>Gjør em skjønnsmessig vurdering av om innholdet i det tilgjengelige navnet, gir tilstrekkelig informasjon om hva som er lenkemålet. Lenkemålet er dit brukeren kommer ved å aktivere lenke
Samme kommentar for filformat som for 111b

2023-12-15 07:00 UTC, geirsf requested changes

2023-12-19 11:47 UTC, geirsf approved these changes

2023-12-19 11:47 UTC, geirsf commented on Testreglar/1.1.1/Nett/nett-1.1.1c.json
> +			"ht": "<p>Bruk kodeverktøyet i nettleseren og sjekk om det finnes et eller flere bilder som er kodet med <code>&lt;map&gt;</code>-elementet.</p>\n<p>Merk: Bildets plassering har ikke betydning. De
```suggestion
			"ht": "<p>Bruk kodeverktøyet i nettleseren og sjekk om det finnes et eller flere bilder som er kodet med <code>&lt;map&gt;</code>-elementet.</p>\n<p><strong>Merk:</strong> Bildets plassering har ikke betydning. Det kan for eksempel ligge i en meny, liste, tabell eller lignende. </p>",
```

2023-12-19 11:54 UTC, janBeniaminKwiek approved these changes

2023-12-19 13:15 UTC, merged