nett 1.1.1d er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #281
Opened 2023-12-05 11:05 UTC by adilsofficial

2023-12-05 11:06 UTC, adilsofficial commented on Testreglar/1.1.1/Nett/nett-1.1.1d.json
> +	"namn": "Nett-1.1.1d CAPTCHA har tekstalternativ og alternativ form",
```suggestion
	"namn": "Nett-1.1.1d CAPTCHA har tekstalternativ og alternativ form 2023",
```

2023-12-06 15:43 UTC, ABJORS approved these changes

2023-12-13 08:42 UTC, janBeniaminKwiek approved these changes

2023-12-15 10:43 UTC, geirsf requested changes

2023-12-15 10:43 UTC, geirsf commented on Testreglar/1.1.1/Nett/nett-1.1.1d.json
> +						"fasit": "Ikkje forekomst",
Ikkje forekomst i delutfall=?

2023-12-19 10:30 UTC, adilsofficial commented on Testreglar/1.1.1/Nett/nett-1.1.1d.json
> +						"fasit": "Ikkje forekomst",
Hva mener du?

2023-12-19 13:58 UTC, geirsf approved these changes

2023-12-19 15:36 UTC, merged