app 3.2.2a er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #292
Opened 2023-12-11 08:28 UTC by adilsofficial

Det finnes ikke en eksisterende testregel for denne testregelen.

2023-12-15 12:47 UTC, geirsf requested changes

2023-12-15 12:47 UTC, geirsf commented on Testreglar/3.2.2/App/app-3.2.2a.json
> +			]
legg til "anna"

2023-12-15 12:47 UTC, geirsf commented on Testreglar/3.2.2/App/app-3.2.2a.json
> +			"ht": "<p>Forsøk å navigere til komponenten du tester.</p>",
Kva type "navigering" er meint her?   Å sveipe til?  Med skjerlesar?

2023-12-19 12:21 UTC, janBeniaminKwiek requested changes

2023-12-19 12:21 UTC, janBeniaminKwiek commented on Testreglar/3.2.2/App/app-3.2.2a.json
> +			"ht": "<p>Gjer ein visuell inspeksjon, og sjekk om du finn informasjon om at det vil skje kontekstendring.</p>\n<p>Informasjonen er synleg og plassert i tråd med eit av følgjande alternativ: </p>\
Mulig endre til: på starten av appsida? og Sveiperekkefølga/leserekkefølga?

2023-12-19 14:02 UTC, geirsf approved these changes

2024-01-09 10:30 UTC, janBeniaminKwiek approved these changes

2024-01-10 09:43 UTC, merged