nett 2.4.2a er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #294
Opened 2023-12-11 08:34 UTC by adilsofficial

2023-12-13 11:24 UTC, ABJORS approved these changes

2023-12-15 13:03 UTC, geirsf approved these changes

2023-12-15 13:03 UTC, geirsf commented on Testreglar/2.4.2/Nett/nett-2.4.2a.json
> +			"ht": "<p>Beskriv innhaldet på nettsida med få ord.</p>\n<p> </p>",
```suggestion
			"ht": "<p>Beskriv innhaldet på nettsida med få ord.</p>",
```

2023-12-15 13:06 UTC, geirsf requested changes

2023-12-15 13:06 UTC, geirsf commented on Testreglar/2.4.2/Nett/nett-2.4.2a.json
> +	"kravTilSamsvar": "<ul>\r\n<li>Sidetittelen er korrekt kodet i det oppmerkingsspråket som er brukt og</li>\r\n<li>Sidetittelen gir en relevant beskrivelse av sidens tema eller  formål</li>\r\n</ul>"
kravTilSamsvar: Oppdateres til å være på nynorsk..

2023-12-19 12:26 UTC, janBeniaminKwiek requested changes

2023-12-19 12:26 UTC, janBeniaminKwiek commented on Testreglar/2.4.2/Nett/nett-2.4.2a.json
> +	"kravTilSamsvar": "<ul>\r\n<li>Sidetittelen er korrekt kodet i det oppmerkingsspråket som er brukt og</li>\r\n<li>Sidetittelen gir en relevant beskrivelse av sidens tema eller  formål</li>\r\n</ul>"
Ekstra mellomrom etter "tema eller"...

2023-12-19 12:26 UTC, janBeniaminKwiek commented on Testreglar/2.4.2/Nett/nett-2.4.2a.json
> +			"ht": "<ul>\n<li>Kopier sidetittel og registrer.</li>\n<li>Sidetittel er gjerne vist i fana på nettlesaren. </li>\n</ul>\n<p><strong>Merk:</strong> Sidetittel ikkje er det same som hovudoverskrift
Hvis vi allerede har inspisert, hvorfor skal vi se på sidetittel i fana i nettleser?

2023-12-19 12:26 UTC, janBeniaminKwiek commented on Testreglar/2.4.2/Nett/nett-2.4.2a.json
> +			"ht": "<p>Sidetittelen skal vere relevant for emne eller formål med sida. Namnet på sida/dokumentet er nok til å gi ein beskrivande sidetittel, men det er ikkje noko krav om å bruke namnet på sida
kom gjerne med et eksempel på relevanse som ikke går på "feil" sidetittel men feil kontekst. Eksempelvis Title: Understanding Success criterion 2.4.3 Focus order Leder til Understanding success criterion 2.4.4 Link Purpose(in context)

2023-12-19 15:07 UTC, adilsofficial commented on Testreglar/2.4.2/Nett/nett-2.4.2a.json
> +	"kravTilSamsvar": "<ul>\r\n<li>Sidetittelen er korrekt kodet i det oppmerkingsspråket som er brukt og</li>\r\n<li>Sidetittelen gir en relevant beskrivelse av sidens tema eller  formål</li>\r\n</ul>"
Det er bokmål på alle testregler.

2023-12-20 13:37 UTC, geirsf commented on Testreglar/2.4.2/Nett/nett-2.4.2a.json
> +	"kravTilSamsvar": "<ul>\r\n<li>Sidetittelen er korrekt kodet i det oppmerkingsspråket som er brukt og</li>\r\n<li>Sidetittelen gir en relevant beskrivelse av sidens tema eller  formål</li>\r\n</ul>"
spraak": "nn", -> Nynorsk

2023-12-20 13:39 UTC, geirsf requested changes

2023-12-20 13:39 UTC, geirsf commented on Testreglar/2.4.2/Nett/nett-2.4.2a.json
> +	"kravTilSamsvar": "<ul>\r\n<li>Sidetittelen er korrekt kodet i det oppmerkingsspråket som er brukt og</li>\r\n<li>Sidetittelen gir en relevant beskrivelse av sidens tema eller formål</li>\r\n</ul>",
Kravet til samsvar skal være på samme målform som resten av testreglen -> NN = Nynorsk

2023-12-20 13:57 UTC, geirsf approved these changes

2024-01-09 10:31 UTC, janBeniaminKwiek approved these changes

2024-01-10 09:53 UTC, merged