app 2.4.4a er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #299
Opened 2023-12-12 12:01 UTC by adilsofficial

Det finnes ikke en eksisterende testregel for denne testregelen.

2023-12-13 11:35 UTC, ABJORS approved these changes

2023-12-13 11:35 UTC, ABJORS commented on Testreglar/2.4.4/App/app-2.4.4a.json
> +			"ht": "<p>Du skal bruke skjermlesar for å finne og teste lenker. </p>\n<p>Slik testar du:</p>\n<p><strong>iOS</strong></p>\n<ul>\n<li>Aktiver VoiceOver rotor \n<ul>\n<li>Innstillinger -&gt; Tilgje
Rotor?

2023-12-15 13:30 UTC, geirsf requested changes

2023-12-15 13:30 UTC, geirsf commented on Testreglar/2.4.4/App/app-2.4.4a.json
> +	"kravTilSamsvar": "<p>Lenker som inneholder tekst oppfyller kravet dersom:</p>\r\n<ul>\r\n<li>Lenketeksten alene beskriver formålet med lenken eller</li>\r\n<li>Lenketeksten sammen med programmering
Samme kommentar som for nett...

2023-12-15 13:30 UTC, geirsf commented on Testreglar/2.4.4/App/app-2.4.4a.json
> +			"ht": "<p>Du skal bruke skjermlesar for å finne og teste lenker. </p>\n<p>Slik testar du:</p>\n<p><strong>iOS</strong></p>\n<ul>\n<li>Aktiver VoiceOver rotor \n<ul>\n<li>Innstillinger -&gt; Tilgje
```suggestion
			"ht": "<p>Du skal bruke skjermlesar for å finne og teste lenker med tekst.</p>\n<p>Slik testar du:</p>\n<p><strong>iOS</strong></p>\n<ul>\n<li>Aktiver VoiceOver rotor \n<ul>\n<li>Innstillinger -&gt; Tilgjengelighet -&gt; VoiceOver -&gt;Rotor</li>\n<li>Velg Lenker i Rotorobjekter</li>\n<li>Skru på Endre roter etter objekt</li>\n</ul>\n</li>\n<li>Aktiver VoiceOver</li>\n<li>Opne appsida</li>\n<li>Bruk rotoren for å navigere mellom lenker (koblinger)</li>\n</ul>\n<p><strong> Android</strong></p>\n<ul>\n<li>Aktiver TalkBack-menyen\n<ul>\n<li>Innstillinger -&gt; Tilgjengelighet -&gt; TalkBack-&gt;Innstillnger -&gt; Tilpass menyer -&gt;Tilpass lesekontrollene</li>\n<li>Velg Linker</li>\n</ul>\n</li>\n<li>Aktiver TalkBack</li>\n<li>Opne appsida</li>\n<li>Bruk TalkBack-menyer for å navigere mellom lenker (koblinger)</li>\n</ul>\n<p><strong>Merk:</strong></p>\n<ul>\n<li>Dersom skjermlesar ikkje les opp lenker, betyr det at appsida ikkje inneheld lenker. </li>\n<li>Lenkas plassering er utan betydning, og kan for eksempel ligge i meny, liste eller tabell.</li>\n<li>Du skal ikkje teste knappar eller lenker som inneheld berre bilde. Dette blir testa i SK 4.1.2 og 1.1.1.</li>\n</ul>",
```

2023-12-15 13:30 UTC, geirsf commented on Testreglar/2.4.4/App/app-2.4.4a.json
> +			"ht": "<p>Du skal bruke skjermlesar for å finne og teste lenker. </p>\n<p>Slik testar du:</p>\n<p><strong>iOS</strong></p>\n<ul>\n<li>Aktiver VoiceOver rotor \n<ul>\n<li>Innstillinger -&gt; Tilgje
"Roter" ->Rotor

2023-12-19 12:36 UTC, janBeniaminKwiek requested changes

2023-12-19 12:36 UTC, janBeniaminKwiek commented on Testreglar/2.4.4/App/app-2.4.4a.json
> +			"ht": "<p>Beskriv lenka, slik at det er mogleg å identifisere den i ettertid. Om du finn fleire lenker registrerer du ei og ei.</p>\n<p><strong>Tips:</strong> Du kan skrive lenketekst, plassering
Standardiser hvordan vi skal registrere.

2023-12-20 13:52 UTC, geirsf approved these changes

2024-01-09 10:32 UTC, janBeniaminKwiek approved these changes

2024-01-10 10:03 UTC, merged