nett 3.1.1a er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #313
Opened 2023-12-22 08:37 UTC by adilsofficial

2024-01-08 11:24 UTC, ABJORS approved these changes

2024-01-09 10:45 UTC, janBeniaminKwiek requested changes

2024-01-09 10:45 UTC, janBeniaminKwiek commented on Testreglar/3.1.1/Nett/nett-3.1.1a.json
> +			"spm": "Er nettsida koda i HTML 4 eller HTML 5?",
Her må det vel være mulig å legge disse sammen til et spørsmål som sender bruker til relevant steg fremfor å ha delsteg 3.1,3.2 og 3.3? Eksempelvis Hvilket språk/språkversjon er nettsiden kodet i: Alt1 HTML4-->3.4, Alt2,HTML5-->3.4, alt3 XHTML1.0-->3.5, alt4 xhtml1.1-->3.6

2024-01-09 10:45 UTC, janBeniaminKwiek commented on Testreglar/3.1.1/Nett/nett-3.1.1a.json
> +			"ht": "<p>Vel det språket som alt eller størsteparten av innhaldet på nettsida har. </p>\n<ul>\n<li>Dersom det er vanskeleg å vurdere kva språk som er mest brukt, er hovudspråket som det språket s
Er det hensiktsmessig å ha med de samiske språkene fremfor bare bokmål, nynorsk og engelsk?

2024-01-09 10:45 UTC, janBeniaminKwiek commented on Testreglar/3.1.1/Nett/nett-3.1.1a.json
> +			"ht": "<p>Vel det språket som alt eller størsteparten av innhaldet på nettsida har. </p>\n<ul>\n<li>Dersom det er vanskeleg å vurdere kva språk som er mest brukt, er hovudspråket som det språket s
Her tror jeg det egentlig kan avsluttes me Kva er hovudspråket--> samsvarer språkkoden med hovudspråket på siden.

2024-01-12 14:22 UTC, geirsf approved these changes

2024-01-12 14:22 UTC, geirsf commented on Testreglar/3.1.1/Nett/nett-3.1.1a.json
> +	"kolonner": [
fjernes

2024-01-15 09:17 UTC, adilsofficial commented on Testreglar/3.1.1/Nett/nett-3.1.1a.json
> +			"spm": "Er nettsida koda i HTML 4 eller HTML 5?",
Det kan brukes radioknapper og ruting basert på alternativer.

2024-01-15 09:24 UTC, adilsofficial commented on Testreglar/3.1.1/Nett/nett-3.1.1a.json
> +			"ht": "<p>Vel det språket som alt eller størsteparten av innhaldet på nettsida har. </p>\n<ul>\n<li>Dersom det er vanskeleg å vurdere kva språk som er mest brukt, er hovudspråket som det språket s
Dette er pga. data hensikten. Vi holder den som den er.

2024-01-16 07:19 UTC, geirsf approved these changes

2024-01-24 07:03 UTC, geirsf approved these changes

2024-01-25 07:28 UTC, janBeniaminKwiek approved these changes

2024-01-25 08:07 UTC, merged