nett 3.1.2a er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #315
Opened 2023-12-22 08:42 UTC by adilsofficial

2024-01-08 10:59 UTC, ABJORS requested changes

2024-01-08 10:59 UTC, ABJORS commented on Testreglar/3.1.2/Nett/nett-3.1.2a.json
> +			"ht": "<p>Beskriv innhaldet er skrive på eit anna språk, enn hovedspråket, slik at det er mogleg å identifisere det i ettertid. Viss det gjeld fleire element, registrerer du eit og eit.</p>\n<p><s
legg til "som" mellom "innhaldet" og "er"

2024-01-08 10:59 UTC, ABJORS commented on Testreglar/3.1.2/Nett/nett-3.1.2a.json
> +			"label": "Innhold som er skrive i eit anna språk:",
På eit anna srålk

2024-01-08 10:59 UTC, ABJORS commented on Testreglar/3.1.2/Nett/nett-3.1.2a.json
> +			"spm": "Samsvarar språkkoden med språket som innhaldet er skrive i?",
skrive på

2024-01-09 10:55 UTC, janBeniaminKwiek requested changes

2024-01-09 10:55 UTC, janBeniaminKwiek commented on Testreglar/3.1.2/Nett/nett-3.1.2a.json
> +			"ht": "<p>Samanlikn språket i innholdet med språkkoden du fann i steg 3.4. </p>\n<p>Sjekk at språkkoden stemmer med språket i innhalkdet.</p>\n<p>Bruk av generell språkkode er tilstrekkeleg:</p>\n
på ei innhold?

2024-01-09 10:55 UTC, janBeniaminKwiek commented on Testreglar/3.1.2/Nett/nett-3.1.2a.json
> +			"spm": "Kva språk er innholdet skrive i?",
Kan ikke denne avsluttes med 3.6: samsvarer språkkoden med språket det er skrevet på ja/nei?

2024-01-12 14:30 UTC, geirsf approved these changes

2024-01-12 14:30 UTC, geirsf commented on Testreglar/3.1.2/Nett/nett-3.1.2a.json
> +	"kolonner": [
fjernes

2024-01-15 09:41 UTC, adilsofficial commented on Testreglar/3.1.2/Nett/nett-3.1.2a.json
> +			"spm": "Kva språk er innholdet skrive i?",
Vi beholder den som den er pga. data hensikten.

2024-01-16 07:24 UTC, geirsf approved these changes

2024-01-24 08:05 UTC, ABJORS approved these changes

2024-01-25 07:29 UTC, janBeniaminKwiek approved these changes

2024-01-25 08:08 UTC, merged