nett 1.3.1a er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #349
Opened 2024-01-10 08:28 UTC by adilsofficial

2024-01-10 10:26 UTC, janBeniaminKwiek requested changes

2024-01-10 10:26 UTC, janBeniaminKwiek commented on Testreglar/1.3.1/Nett/nett-1.3.1.json
> +			"ht": "<p>Du kan bruke:</p>\n<p><strong>Alternativ 1</strong></p>\n<ul>\n<li>Kodeverktøyet i nettleseren til å sjekke dette</li>\n<li>I standard HTML: Overskriftene er kodet med elementene <code>&
Extension viser ikke headings som har aria-hidden. Er denne gjennomtestet?

2024-01-10 10:26 UTC, janBeniaminKwiek commented on Testreglar/1.3.1/Nett/nett-1.3.1.json
> +			"spm": "Inngår den visuelle overskriften i et tydelig overskriftshierarki?",
Litt bedre forklaring av hva tydelig overskriftshierarki er

2024-01-10 10:26 UTC, janBeniaminKwiek commented on Testreglar/1.3.1/Nett/nett-1.3.1.json
> +			"ht": "<p>Slik tester du</p>\n<ul>\n<li>Sammenlign nivået på den visuelle overskriften med de forrige overskriftene.</li>\n<li>Start på toppen av overskriftshierarkiet og tell deg nedover.</li>\n<
Bedre standardisering på nivå er ønskelig.

2024-01-10 10:26 UTC, janBeniaminKwiek commented on Testreglar/1.3.1/Nett/nett-1.3.1.json
> +			"ht": "<p>Du kan bruke kodeverktøyet i nettleseren eller Chrome-extension headingsMap til å sjekke dette.</p>\n<p>Overskriftene skal være kodet med rett nivå:</p>\n<ul>\n<li>I standard HTML er ove
Hvorfor krever Chrome ext å lese nettleserloggen min?

2024-01-10 10:26 UTC, janBeniaminKwiek commented on Testreglar/1.3.1/Nett/nett-1.3.1.json
> +			"ht": "<p><strong>Alternativ 1</strong></p>\n<ul>\n<li>Inspiser overskriften i nettleseren</li>\n<li>Bruk Accessibility Checker verktøy i inspiser</li>\n<li>Under Computed Properties i Accessibili
Er accessibility checker det samme som accessibility panelet? 
![image](https://github.com/TilsynForUniversellUtforming/testreglar-wcag-2.x/assets/122993143/a2424a6c-1001-4431-9173-6b810c918c3a)

2024-01-15 09:51 UTC, adilsofficial commented on Testreglar/1.3.1/Nett/nett-1.3.1.json
> +			"ht": "<p>Du kan bruke kodeverktøyet i nettleseren eller Chrome-extension headingsMap til å sjekke dette.</p>\n<p>Overskriftene skal være kodet med rett nivå:</p>\n<ul>\n<li>I standard HTML er ove
Finnnes et annet alternativ eller fjernes.

2024-01-18 12:44 UTC, geirsf approved these changes

2024-01-25 08:51 UTC, ABJORS approved these changes

2024-01-29 12:17 UTC, adilsofficial commented on Testreglar/1.3.1/Nett/nett-1.3.1.json
> +			"spm": "Inngår den visuelle overskriften i et tydelig overskriftshierarki?",
fysisk adskilt *

2024-01-29 12:17 UTC, adilsofficial commented on Testreglar/1.3.1/Nett/nett-1.3.1.json
> +			"ht": "<p>Slik tester du</p>\n<ul>\n<li>Sammenlign nivået på den visuelle overskriften med de forrige overskriftene.</li>\n<li>Start på toppen av overskriftshierarkiet og tell deg nedover.</li>\n<
Vi lager et nytt forslag på dette.

2024-01-29 12:17 UTC, adilsofficial commented on Testreglar/1.3.1/Nett/nett-1.3.1.json
> +			"ht": "<p><strong>Alternativ 1</strong></p>\n<ul>\n<li>Inspiser overskriften i nettleseren</li>\n<li>Bruk Accessibility Checker verktøy i inspiser</li>\n<li>Under Computed Properties i Accessibili
Ja

2024-01-29 12:17 UTC, adilsofficial commented on Testreglar/1.3.1/Nett/nett-1.3.1.json
> +			"ht": "<p>Du kan bruke kodeverktøyet i nettleseren eller Chrome-extension headingsMap til å sjekke dette.</p>\n<p>Overskriftene skal være kodet med rett nivå:</p>\n<ul>\n<li>I standard HTML er ove
Fjernes

2024-02-19 11:05 UTC, adilsofficial commented on Testreglar/1.3.1/Nett/nett-1.3.1.json
> +			"spm": "Inngår den visuelle overskriften i et tydelig overskriftshierarki?",
@janBeniaminKwiek Beholdes som den er. Nærmere presisering kommer gjennom bruk.

2024-03-12 11:42 UTC, janBeniaminKwiek approved these changes

2024-03-12 14:22 UTC, geirsf requested changes

2024-03-12 14:42 UTC, geirsf approved these changes

2024-03-13 09:55 UTC, merged