nett-1.3.1c er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #351
Opened 2024-01-10 08:37 UTC by adilsofficial

2024-01-23 07:48 UTC, geirsf requested changes

2024-01-23 07:48 UTC, geirsf commented on Testreglar/1.3.1/Nett/nett-1.3.1c.json
> +								"type": "gaaTil",
Hvorfor skal du hoppe til 3.10 her?

2024-01-23 07:56 UTC, geirsf requested changes

2024-01-23 07:56 UTC, geirsf commented on Testreglar/1.3.1/Nett/nett-1.3.1c.json
> +			"ht": "<p><strong>Alternativ 1</strong></p>\n<ul>\n<li>Inspiser listen i nettleseren</li>\n<li>Bruk Accessibility Checker verktøy i inspiser</li>\n<li>Under Computed Properties i Accessibility Che
```suggestion
			"ht": "<p><strong>Alternativ 1</strong></p>\n<ul>\n<li>Inspiser listen i nettleseren</li>\n<li>Bruk Accessibility Checker verktøy i inspiser</li>\n<li>Under Computed Properties i Accessibility Checker</li>\n<li>Sjekk om det står informasjon \"Accessibility node not exposed\"</li>\n</ul>\n<p><strong>Alternativ 2</strong></p>\n<p>Sjekk i koden om listen er kodet med et av følgende attributter:</p>\n<ul>\n<li><code>role=\"presentation\"</code></li>\n<li><code>role=\"none\"</code></li>\n<li><code>aria-hidden=\"true\"</code></li>\n</ul>",
```

2024-01-25 08:03 UTC, janBeniaminKwiek requested changes

2024-01-25 12:58 UTC, ABJORS approved these changes

2024-01-26 14:22 UTC, adilsofficial commented on Testreglar/1.3.1/Nett/nett-1.3.1c.json
> +			"spm": "Er listen slik at den ignoreres av hjelpemiddelteknologi?",
Rutingen er riktig, steg nr er ikke viktig.

2024-01-30 10:45 UTC, geirsf approved these changes

2024-02-06 07:43 UTC, janBeniaminKwiek approved these changes

2024-02-06 09:04 UTC, merged