nett-1.3.1d er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #354
Opened 2024-01-12 09:51 UTC by adilsofficial

2024-01-25 08:09 UTC, janBeniaminKwiek requested changes

2024-01-25 08:09 UTC, janBeniaminKwiek commented on Testreglar/1.3.1/Nett/nett-1.3.1d.json
> +				"Nettstedets logo og navn",
savner et litt klarere skille på  "reklame, annonser og lignende" og "andre seksjoner av innhold" og hva som skal i hver. Det er ikke alltid veldig klart om noe er reklame eller promotering osv.

2024-01-29 12:22 UTC, adilsofficial commented on Testreglar/1.3.1/Nett/nett-1.3.1d.json
> +				"Nettstedets logo og navn",
Vi beholder den som den er i dag.

2024-01-31 14:11 UTC, geirsf requested changes

2024-01-31 14:11 UTC, geirsf commented on Testreglar/1.3.1/Nett/nett-1.3.1d.json
> +			"spm": "Er regionen kodet med &lt;header&gt;-element eller role=\"banner\"?",
Hva er kilden til at vi alltid krever at "Nettstedets logo og navn" skal være et landemerke?

2024-01-31 14:11 UTC, geirsf commented on Testreglar/1.3.1/Nett/nett-1.3.1d.json
> +			"ht": "<p><strong>Alternativ 1</strong></p>\n<ul>\n<li>Inspiser regionen i nettleseren dvs. parent-element til regionen</li>\n<li>Bruk Accessibility Checker verktøy i inspiser</li>\n<li>Under Comp
Foreslår å snu rekkefølgen på role="navigation" og `<nav>` -element slik at vi får HTML5 alternativet først.

2024-01-31 14:11 UTC, geirsf commented on Testreglar/1.3.1/Nett/nett-1.3.1d.json
> +				"Nettstedets logo og navn",
Hva er kilde til at "Reklame, annonser eller lignende" alltid skal være en region?

2024-02-02 08:33 UTC, adilsofficial commented on Testreglar/1.3.1/Nett/nett-1.3.1d.json
> +				"Nettstedets logo og navn",
> Hvor kommer denne listen fra? WAI-ARIA speken (som vises til i Aria 11) bruker disse: [banner](https://www.w3.org/TR/wai-aria/#banner) [complementary](https://www.w3.org/TR/wai-aria/#complementary) [contentinfo](https://www.w3.org/TR/wai-aria/#contentinfo) [form](https://www.w3.org/TR/wai-aria/#form) [main](https://www.w3.org/TR/wai-aria/#main) [navigation](https://www.w3.org/TR/wai-aria/#navigation) [region](https://www.w3.org/TR/wai-aria/#region) [search](https://www.w3.org/TR/wai-aria/#search)

Ja, denne listen er basert på ARIA11 og alternativer som vi har lagt inn er basert på definisjon til alle disse regioner og example 1 fra aria11.



> Hva er kilde at "Reklame, annonser eller lignende" alltid skal være en region?

Kilde: Aria11 example 1, men det er ikke et krav at det alltid skal være en region. Hvis slik seksjon av innholdet er presentert i en del av tydelig visuell inndeling av innhold på nettsiden (dette er et forutsetning for alle disse regioner), så skal det gjenspeiles i koden.

2024-02-02 08:36 UTC, adilsofficial commented on Testreglar/1.3.1/Nett/nett-1.3.1d.json
> +			"spm": "Er regionen kodet med &lt;header&gt;-element eller role=\"banner\"?",
Forutsetning er at hvis innholdet er presentert i en del av tydelig visuell inndeling av innhold på nettsiden, så skal det gjenspeiles i koden med relevante landemerke.

2024-02-05 09:13 UTC, adilsofficial commented on Testreglar/1.3.1/Nett/nett-1.3.1d.json
> +				"Nettstedets logo og navn",
Sett rollen i parentes i steg 2.2 og 3.2.

2024-02-06 07:44 UTC, janBeniaminKwiek approved these changes

2024-02-07 08:13 UTC, geirsf approved these changes

2024-02-07 08:36 UTC, merged