Bug: Manglende labels #363
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #365
Opened 2024-01-17 09:12 UTC by adilsofficial

2024-01-17 10:01 UTC, geirsf requested changes

2024-01-17 10:01 UTC, geirsf commented on Testreglar/1.4.10/Nett/nett-1.4.10a.json
> +			"label": "Innhold og funksjonlaitet:",
```suggestion
			"label": "Innhold og funksjonalitet:",
```

2024-01-17 10:01 UTC, geirsf commented on Testreglar/1.4.10/App/app-1.4.10a.json
> +			"label": "Innhold og funksjonlaitet:",
```suggestion
			"label": "Innhold og funksjonalitet:",
```

2024-01-18 12:25 UTC, geirsf approved these changes

2024-01-18 12:25 UTC, geirsf commented on Testreglar/1.2.5/Nett/nett-1.2.5a.json
> +			"label": "Stikkprøver:",
```suggestion
			"label": "Stikkprøve:",
```

2024-01-18 12:25 UTC, geirsf commented on Testreglar/1.2.5/Nett/nett-1.2.5a.json
> +			"label": "Stikkprøver:",
entall?

2024-01-18 12:25 UTC, geirsf commented on Testreglar/1.2.5/App/app-1.2.5a.json
> +			"label": "Stikkprøver:",
```suggestion
			"label": "Stikkprøve:",
```

2024-01-18 12:25 UTC, geirsf commented on Testreglar/1.2.5/App/app-1.2.5a.json
> +			"label": "Stikkprøver:",
entall, ref Registrer en og en stikkprøve med tidsstempel

2024-01-19 11:52 UTC, geirsf approved these changes

2024-01-19 11:52 UTC, geirsf commented on Testreglar/1.3.5/App/app-1.3.5a.json
> +			"label": "Inndataelement:",
```suggestion
			"label": "Skjemaelementet:",
```

2024-01-19 11:52 UTC, geirsf commented on Testreglar/1.4.10/App/app-1.4.10a.json
> +			"label": "Innhold og funksjonalitet:",
```suggestion
			"label": "Innhold eller funksjonalitet:",
```

2024-01-19 11:52 UTC, geirsf commented on Testreglar/1.4.10/Nett/nett-1.4.10a.json
> +			"label": "Innhold og funksjonalitet:",
```suggestion
			"label": "Innhold eller funksjonalitet:",
```

2024-01-19 11:54 UTC, Sivzilla82 approved these changes

2024-01-19 11:54 UTC, merged