nett-1.3.1e er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #374
Opened 2024-01-19 09:29 UTC by adilsofficial

2024-01-25 08:15 UTC, janBeniaminKwiek requested changes

2024-01-25 08:15 UTC, janBeniaminKwiek commented on Testreglar/1.3.1/Nett/nett-1.3.1e.json
> +			"ht": "<p>Hvis instruksjonen har en tydelig visuell relasjon til et skjemaelement eller en gruppe av skjemaelementer, skal dette også ivaretas i koden.</p>\n<p>Slik tester du:</p>\n<ul>\n<li>Gjør
Her bør vi spesifisere enda mer av hva som er tydelig visuell relasjon. Siste del er veldig bra mens første del gir veldig mye rom for skjønnsmessig vurdering som kan gjøre at vi tester forskjellig.

2024-01-25 13:51 UTC, ABJORS approved these changes

2024-01-25 13:51 UTC, ABJORS commented on Testreglar/1.3.1/Nett/nett-1.3.1e.json
> +			"spm": "Hva skjema tester du?",
"Hvilket" på bokmål og "kva" på nynorsk

2024-02-02 09:08 UTC, geirsf approved these changes
God jobba, mye vanskelige definisjoner her.

2024-02-06 07:46 UTC, janBeniaminKwiek approved these changes

2024-02-06 09:05 UTC, merged