nett 3.3.4a er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #386
Opened 2024-01-24 13:07 UTC by adilsofficial

Vi oppfordrer dere til teste denne testregelen og rutingen grundig. Vi har testet mye, men det er ekstra viktig at dere tester den i ks-runden grundig.

2024-01-30 09:28 UTC, ABJORS approved these changes

2024-01-30 09:28 UTC, ABJORS commented on Testreglar/3.3.4/Nett/nett-3.3.4a.json
> +			"spm": "Det tilstrekkelig at ett av alternativene i kravet er oppfylt. Hvert alternativ har sitt eget sett med krav til samsvar. ",
Det "ER" tilstrekkelig

2024-02-01 09:23 UTC, janBeniaminKwiek approved these changes

2024-02-02 09:29 UTC, geirsf requested changes

2024-02-02 09:29 UTC, geirsf commented on Testreglar/3.3.4/Nett/nett-3.3.4a.json
> +			"spm": "Det tilstrekkelig at ett av alternativene i kravet er oppfylt. Hvert alternativ har sitt eget sett med krav til samsvar. ",
Det er litt utklart hva som er instruksjonen har. Må tydeliggjøres hva det er forventet at testeren skal gjøre på dette steget.

2024-02-05 09:58 UTC, adilsofficial commented on Testreglar/3.3.4/Nett/nett-3.3.4a.json
> +			"spm": "Det tilstrekkelig at ett av alternativene i kravet er oppfylt. Hvert alternativ har sitt eget sett med krav til samsvar. ",
Fjernes.

2024-02-05 09:59 UTC, adilsofficial commented on Testreglar/3.3.4/Nett/nett-3.3.4a.json
> +			"spm": "Det tilstrekkelig at ett av alternativene i kravet er oppfylt. Hvert alternativ har sitt eget sett med krav til samsvar. ",
Steger har blitt fjernet.

2024-02-09 13:55 UTC, geirsf approved these changes

2024-02-12 07:53 UTC, merged