nett-1.2.2a er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #424
Opened 2024-02-09 11:19 UTC by adilsofficial

2024-02-14 12:25 UTC, janBeniaminKwiek requested changes

2024-02-15 09:06 UTC, geirsf requested changes

2024-02-15 09:06 UTC, geirsf commented on Testreglar/1.2.2/Nett/nett-1.2.2a.json
> +					"utfall": "#delutfall(0,Ja) #delutfall(1,Ja) Videoen har et tilgjengelig navn som ikke gir en beskrivende identifikasjon."
Som sagt før, litt skeptisk til  ta med ting som er ok, nå det er snakk om ikke-samsvar,

2024-02-15 15:58 UTC, ABJORS requested changes
Tror det er lurt å generalisere/gjenbruke utfall.

2024-02-19 11:28 UTC, adilsofficial commented on Testreglar/1.2.2/Nett/nett-1.2.2a.json
> +			"ht": "<p>Slik tester du:</p>\n<ul>\n<li>Gjør en visuell inspeksjon, og sjekk om testsiden har video med lyd</li>\n<li>Hvis videoen er lang, tar du stikkprøver på minst to steder </li>\n</ul>",
Fikset med tre stikkprøver og lang video=over 5 minutter.

2024-02-19 11:28 UTC, adilsofficial commented on Testreglar/1.2.2/Nett/nett-1.2.2a.json
> +			"spm": "Er videoen forhåndsinnspilt (opptak)?",
Dette er bare eksempler, men hvis en tester vet at videoen er forhåndsinnspilt, så får man heller si det i kommentar.

2024-02-19 11:28 UTC, adilsofficial commented on Testreglar/1.2.2/Nett/nett-1.2.2a.json
> +			"spm": "Har videoen et tilgjengelig navn, som ikke er tomt?",
Det er forklart i merknaden i steg 3.14. Vi har flyttet denne merknaden til 3.13.

2024-02-23 11:00 UTC, ABJORS requested changes

2024-02-23 11:00 UTC, ABJORS commented on Testreglar/1.2.2/Nett/nett-1.2.2a.json
> +			"ht": "<p>Slik tester du:</p>\n<ul>\n<li>Start videoen</li>\n<li>Gjør en visuell inspeksjon av tekstingen, og og sjekk om tekstingen lesbar</li>\n<li>Ta minst tre stikkprøver i ulike deler av vide
Siste setning: står "SK 143" skal kanskje stå "SK 1.4.3"?

2024-02-23 11:00 UTC, ABJORS commented on Testreglar/1.2.2/Nett/nett-1.2.2a.json
> +			"ht": "<p><strong>Merk:</strong> Det er teksting og bilde til sammen, som skal formidle informasjon gitt via bilde og lyd i videoen.</p>\n<p>Slik tester du:</p>\n<ul>\n<li>Se gjennom de første et
Setning "Se gjennom de første et min av videoen" hva menes her? Enten: "Se gjennom de første minuttene av videoen" eller "Se gjennom det første minuttet av videoen"

2024-02-23 11:00 UTC, ABJORS commented on Testreglar/1.2.2/Nett/nett-1.2.2a.json
> +					"steg": "3.13",
Hvis dette steget hører til SK 1.1.1 tror jeg at det er bedre å lage en egen testregel på dette.

2024-02-27 09:13 UTC, adilsofficial commented on Testreglar/1.2.2/Nett/nett-1.2.2a.json
> +					"steg": "3.13",
Ok. Vi lager en egen testregel på dette https://github.com/TilsynForUniversellUtforming/testreglar-wcag-2.x/issues/451

2024-03-05 09:42 UTC, adilsofficial commented
@geirsf  @janBeniaminKwiek @ABJORS Nå er testregelen klar for ny vurdering.

2024-03-06 09:51 UTC, geirsf approved these changes
Se over krav til samsvar.

2024-03-06 09:51 UTC, geirsf commented on Testreglar/1.2.2/Nett/nett-1.2.2a.json
> +	"kravTilSamsvar": "<p>Forhåndsinnspilt video med lyd har teksting eller tekstalternativ.</p><ul><li>Teksting skal formidle tale og lyd som er viktig for å forstå videoen. I dialog skal det markeres
"Video har et tilgjengelig navn som gir beskrivende identifikasjon av videoen"   Dette er vell tatt ut nå?

2024-03-12 09:02 UTC, ABJORS approved these changes

2024-03-12 11:43 UTC, janBeniaminKwiek approved these changes

2024-03-13 10:00 UTC, adilsofficial commented on Testreglar/1.2.2/Nett/nett-1.2.2a.json
> +	"kravTilSamsvar": "<p>Forhåndsinnspilt video med lyd har teksting eller tekstalternativ.</p><ul><li>Teksting skal formidle tale og lyd som er viktig for å forstå videoen. I dialog skal det markeres
Ja

2024-03-13 10:11 UTC, merged