app-1.2.2a er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #426
Opened 2024-02-09 11:56 UTC by adilsofficial

2024-02-14 12:28 UTC, janBeniaminKwiek reviewed
De samme kommentarene som gjaldt for nett-1.2.2 er også relevante og gjeldende her.

2024-02-14 12:28 UTC, janBeniaminKwiek commented on Testreglar/1.2.2/App/app-1.2.2a.json
> +			"spm": "Er videoen tekstet?",
Samme kommentar som nett.

2024-02-14 12:28 UTC, janBeniaminKwiek commented on Testreglar/1.2.2/App/app-1.2.2a.json
> +			"ht": "<p>Slik tester du</p>\n<ul>\n<li>Se om det er en knapp eller lignende i videospilleren, som slår på/av teksting</li>\n</ul>\n<p><strong>Merk:</strong> Du ofte må føre musepeker over videoen
Musepeker?

2024-02-14 12:28 UTC, janBeniaminKwiek requested changes
De samme observasjonene som gjaldt for nett-1.2.2 er også relevante og gjeldende her.

2024-02-15 16:00 UTC, ABJORS requested changes
Er det mulig å forenkle utfallene her? både med tanke på kompleksitet i utvikling, forvaltning og databehandling

2024-02-19 11:38 UTC, adilsofficial commented on Testreglar/1.2.2/App/app-1.2.2a.json
> +					"utfall": "#delutfall(0,Ja) #delutfall(1,Ja) Videoen har et tilgjengelig navn som ikke gir en beskrivende identifikasjon."
Fjernet.

2024-02-19 11:38 UTC, adilsofficial commented on Testreglar/1.2.2/App/app-1.2.2a.json
> +					"utfall": "#delutfall(0,Ja) #delutfall(1,Ja) Videoen har ikke et tilgjengelig navn."
Fjernet.

2024-02-19 11:42 UTC, adilsofficial commented
@ABJORS kom gjerne med konkrete forslag til forenklinger. Vi har fjernet samsvar delen i utfall med brudd.

2024-02-23 11:23 UTC, ABJORS requested changes

2024-02-23 11:23 UTC, ABJORS commented on Testreglar/1.2.2/App/app-1.2.2a.json
> +			"ht": "<p>Slik tester du:</p>\n<ul>\n<li>Gjør en visuell inspeksjon, og sjekk om appsiden har video med lyd</li>\n<li>Hvis videoen er over 5 minutter, tar du stikkprøver på minst tre steder </li>\
Hva skal du gjøre hvis videoen er under 5 minutter? Teste hele videoen? Her tester du kun om videoen har lyd sant?

2024-02-23 11:23 UTC, ABJORS commented on Testreglar/1.2.2/App/app-1.2.2a.json
> +			"ht": "<p>Slik tester du:</p>\n<ul>\n<li>Start videoen</li>\n<li>Gjør en visuell inspeksjon av tekstingen, og og sjekk om tekstingen lesbar</li>\n<li>Ta minst tre stikkprøver i ulike deler av vide
Endre til "SK 1.4.3"

2024-02-23 11:23 UTC, ABJORS commented on Testreglar/1.2.2/App/app-1.2.2a.json
> +			"ht": "<p><strong>Merk:</strong> Det er teksting og bilde til sammen, som skal formidle informasjon gitt via bilde og lyd i videoen.</p>\n<p>Slik tester du:</p>\n<ul>\n<li>Se gjennom de første et
Samme kommentar som for nett: skriv om første kulepunkt "Se gjennom..."

2024-02-23 11:23 UTC, ABJORS commented on Testreglar/1.2.2/App/app-1.2.2a.json
> +			"ht": "<p>Slik tester du:</p>\n<ul>\n<li>Aktiver skjermleser (opplesingsfunksjon)\n<ul>\n<li>iOS: VoiceOver</li>\n<li>Android: TalkBack</li>\n</ul>\n</li>\n<li>Last appsiden på nytt, etter hver av
Tror dette bør testes under 1.1.1. Hvis det registreres brudd her så vil de blir registrert som brudd på 1.2.2. og ikke 1.1.1 det er uheldig.

2024-02-27 09:22 UTC, adilsofficial commented on Testreglar/1.2.2/App/app-1.2.2a.json
> +			"ht": "<p>Slik tester du:</p>\n<ul>\n<li>Gjør en visuell inspeksjon, og sjekk om appsiden har video med lyd</li>\n<li>Hvis videoen er over 5 minutter, tar du stikkprøver på minst tre steder </li>\
@Sivzilla82 fikser den.

2024-02-27 09:22 UTC, adilsofficial commented on Testreglar/1.2.2/App/app-1.2.2a.json
> +			"ht": "<p>Slik tester du:</p>\n<ul>\n<li>Aktiver skjermleser (opplesingsfunksjon)\n<ul>\n<li>iOS: VoiceOver</li>\n<li>Android: TalkBack</li>\n</ul>\n</li>\n<li>Last appsiden på nytt, etter hver av
https://github.com/TilsynForUniversellUtforming/testreglar-wcag-2.x/issues/451

2024-02-27 13:02 UTC, geirsf commented
vurderes på nytt etter splitting.

2024-03-04 09:31 UTC, Sivzilla82 commented on Testreglar/1.2.2/App/app-1.2.2a.json
> +			"ht": "<p>Slik tester du:</p>\n<ul>\n<li>Gjør en visuell inspeksjon, og sjekk om appsiden har video med lyd</li>\n<li>Hvis videoen er over 5 minutter, tar du stikkprøver på minst tre steder </li>\
Begge testregler er oppdatert, jf. gjennomgang på møte. :)

2024-03-05 11:35 UTC, adilsofficial commented on Testreglar/1.2.2/App/app-1.2.2a.json
> +			"ht": "<p>For å være mediealternativ skal videoen:</p>\n<ul>\n<li>ikke presentere mer informasjon enn det som gis via tekst og</li>\n<li>være tydelig merket. Det vil si\n<ul>\n<li>være plassert i
```suggestion
			"ht": "<p>For å være mediealternativ skal videoen:</p>\n<ul>\n<li>ikke presentere mer informasjon enn det som gis via tekst og</li>\n<li>være tydelig merket. Det vil si\n<ul>\n<li>være plassert i direkte tilknytning til aktuell tekst og</li>\n<li>gi informasjon som viser at det er et mediealternativ</li>\n</ul>\n</li>\n</ul>\n<p>Slik tester du:</p>\n<ul>\n<li>Undersøk om det i tilknytning til videoen, er en tekst som fremstår som hovedformatet for formidling av informasjonen</li>\n<li>Momenter som tilsier at videoen er et mediealternativ til tekst kan være:\n<ul>\n<li>Ikon, for eksempel kamera-ikon</li>\n<li>Lenke med lenketekst som viser til en video, for eksempel \"Se opptak\", \"Animasjon\"</li>\n</ul>\n</li>\n<li>Sjekk at videoen ikke presenterer mer informasjon enn det som gis via teksten</li>\n</ul>",
```

2024-03-06 09:57 UTC, geirsf approved these changes
Korrigere krav til samsvar

2024-03-12 09:03 UTC, ABJORS approved these changes

2024-03-12 11:44 UTC, janBeniaminKwiek approved these changes

2024-03-13 10:14 UTC, merged