nett-1.3.3a er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #439
Opened 2024-02-21 07:42 UTC by adilsofficial

2024-02-21 08:57 UTC, janBeniaminKwiek requested changes

2024-02-21 08:57 UTC, janBeniaminKwiek commented on Testreglar/1.3.3/Nett/nett-1.3.3a.json
> +			"spm": "Er rekkefølga det blir vist til i instruksjonen, den same som leserekkefølga i koden?",
Skal ikke dette testes i 1.3.2?

2024-02-23 11:49 UTC, ABJORS approved these changes
Bør sjekke ut kommentar fra JB. Generelt bør test av krav til samsvar knytt til et SK gjennomføres i en testregel som er knytt til SK.

2024-02-27 09:24 UTC, adilsofficial commented on Testreglar/1.3.3/Nett/nett-1.3.3a.json
> +			"spm": "Er rekkefølga det blir vist til i instruksjonen, den same som leserekkefølga i koden?",
Her sjekker vi instruksjon dvs. om det som ble sagt i instruksjon stemmer.

2024-02-27 13:05 UTC, geirsf approved these changes

2024-03-12 11:44 UTC, janBeniaminKwiek approved these changes

2024-03-14 09:25 UTC, merged