app-2.2.2b er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #444
Opened 2024-02-22 11:48 UTC by adilsofficial

2024-03-04 13:41 UTC, janBeniaminKwiek requested changes

2024-03-04 13:41 UTC, janBeniaminKwiek commented on Testreglar/2.2.2/App/app-2.2.2b.json
> +			"spm": "Oppdaterer innhaldet seg automatisk, før det har gått 1 minutt?",
1 minutt er veldig lenge å vente per testelement

2024-03-04 13:41 UTC, janBeniaminKwiek commented on Testreglar/2.2.2/App/app-2.2.2b.json
> +			"spm": "Blir innhaldet sett på pause, stoppa, skjult, eller får det endra oppdateringsfrekvens?",
Er det noe krav til hvor mye du skal få endret oppdateringsfrekvensen?

2024-03-04 13:41 UTC, janBeniaminKwiek commented on Testreglar/2.2.2/App/app-2.2.2b.json
> +			"spm": "Har innhaldet som blir oppdatert automatisk ein form for bevegelse, blinking eller rulling som varar i meir enn fem sekund?",
Har dere noen praktiske eksempler på dette?

2024-03-11 13:18 UTC, geirsf commented on Testreglar/2.2.2/App/app-2.2.2b.json
> +	"kravTilSamsvar": "<p>For innhold som oppdateres automatisk, uten å bevege seg, gjelder følgende</p>\r\n<ul>\r\n<li>Det er en mekanisme for å pause, stoppe eller skjule innholdet eller styre oppdate
```suggestion
	"kravTilSamsvar": "<p>For innhold som oppdateres automatisk, uten å bevege seg, gjelder følgende</p><ul><li>Det er en mekanisme for å pause, stoppe eller skjule innholdet eller styre oppdateringsfrekvensen og<ul><li>Mekanismen ligger enten på starten av appsiden eller i direkte tilknytning til innholdet eller</li></ul></li><li>Det finnes en dokumentert tastatursnarvei for å pause, stoppe eller skjule innholdet eller styre oppdateringsfrekvensen</li></ul>",
```

2024-03-11 13:19 UTC, geirsf commented on Testreglar/2.2.2/App/app-2.2.2b.json
> +			"ht": "<p>Gjer ein visuell inspeksjon og sjekk om det finst innhald som blir oppdatert automatisk.</p>\n<p>Eksempel på denne typen innhald er</p>\n<ul>\n<li>børsoppdateringar i sanntid</li>\n<li>v
```suggestion
			"ht": "<p>Gjer ein visuell inspeksjon og sjekk om det finst innhald som blir oppdatert automatisk.</p><p>Eksempel på denne typen innhald er</p><ul><li>børsoppdateringar i sanntid</li><li>vêrmeldingar</li><li>nyheitsstraumar</li></ul>",
```

2024-03-11 13:19 UTC, geirsf commented on Testreglar/2.2.2/App/app-2.2.2b.json
> +			"ht": "<p>Beskriv innhaldet som blir oppdatert automatisk, slik at det er mogleg å identifisere det i ettertid.</p>\n<p>Viss det gjeld fleire element, registrerer du eit og eit.</p>",
```suggestion
			"ht": "<p>Beskriv innhaldet som blir oppdatert automatisk, slik at det er mogleg å identifisere det i ettertid.</p><p>Viss det gjeld fleire element, registrerer du eit og eit.</p>",
```

2024-03-11 13:21 UTC, geirsf commented on Testreglar/2.2.2/App/app-2.2.2b.json
> +					"utfall": "Det er ikkje mogleg å pause, stoppe eller skjule innhald som automatisk bevegar seg, blinkar eller rullar."
```suggestion
					"utfall": "Det er ikkje mogleg å pause, stoppe eller skjule innhald som blir oppdatert automatisk."
```

2024-03-11 13:22 UTC, geirsf commented on Testreglar/2.2.2/App/app-2.2.2b.json
> +			"ht": "<p>Avgjerande (nødvendige) handlingar er typisk noko som skjer i sanntid, og kor det å pause/stoppe/skjule vil gjere handlinga ugyldig.</p>\n<p>Eksempel kan vere handel på børs, aksjon, klo
```suggestion
			"ht": "<p>Avgjerande (nødvendige) handlingar er typisk noko som skjer i sanntid, og kor det å pause/stoppe/skjule vil gjere handlinga ugyldig.</p><p>Eksempel kan vere handel på børs, aksjon, klokke og liknande situasjonar der brukaren treng live-oppdateringar.</p>",
```

2024-03-11 13:23 UTC, geirsf commented on Testreglar/2.2.2/App/app-2.2.2b.json
> +			"ht": "<p>Mekanismen kan for eksempel vere ein stopp- eller pauseknapp. Mekanisme for å endre oppdateringsfrekvensen, kan for eksempel vere ei nedtrekksliste med ulike oppdateringsalternativ.</p>\
```suggestion
			"ht": "<p>Mekanismen kan for eksempel vere ein stopp- eller pauseknapp. Mekanisme for å endre oppdateringsfrekvensen, kan for eksempel vere ei nedtrekksliste med ulike oppdateringsalternativ.</p><p><strong>Merk:</strong> Det er ikkje tilstrekkeleg at innhaldet pauser/stoppar berre når det er i fokus.</p>",
```

2024-03-11 13:24 UTC, geirsf commented on Testreglar/2.2.2/App/app-2.2.2b.json
> +			"ht": "<p>Gjer ein visuell inspeksjon og sjekk om mekanismen er plassert nær starten av appsida.</p>\n<p><strong>Merk:</strong> Du skal ikkje måtte scrolle vekk frå starten av sida for å nå mekani
```suggestion
			"ht": "<p>Gjer ein visuell inspeksjon og sjekk om mekanismen er plassert nær starten av appsida.</p><p><strong>Merk:</strong> Du skal ikkje måtte scrolle vekk frå starten av sida for å nå mekanismen.</p>",
```

2024-03-11 13:25 UTC, geirsf commented on Testreglar/2.2.2/App/app-2.2.2b.json
> +	"kravTilSamsvar": "<p>For innhold som oppdateres automatisk, uten å bevege seg, gjelder følgende</p>\r\n<ul>\r\n<li>Det er en mekanisme for å pause, stoppe eller skjule innholdet eller styre oppdate
Kravet om at innholdet må vises samtidig med annet innhold må gå frem her.

2024-03-12 12:46 UTC, adilsofficial commented on Testreglar/2.2.2/App/app-2.2.2b.json
> +			"spm": "Blir innhaldet sett på pause, stoppa, skjult, eller får det endra oppdateringsfrekvens?",
Vi har ikke funnet informasjon om hvor mye du skal få endret oppdateringsfrekvensen hverken i kravet, forståartikkelen eller teknikker.

2024-03-12 12:51 UTC, adilsofficial commented on Testreglar/2.2.2/App/app-2.2.2b.json
> +			"ht": "<p>Automatisk oppdatert innhald som begevar seg, blinkar eller rullar i meir enn fem sekund blir testa i testregel App-2.2.2a.</p>",
```suggestion
			"ht": "<p>Automatisk oppdatert innhald som begevar seg, blinkar eller rullar i meir enn fem sekund blir testa i testregel App-2.2.2a.</p><p>For eksempel, eit banner som rullar i ein nyhetssak som seier \"Akkurat nå\", \"Direkte\", \"Siste nytt\" eller reklamer eller annonser på nett.</p>",
```

2024-03-12 12:53 UTC, adilsofficial commented on Testreglar/2.2.2/App/app-2.2.2b.json
> +	"kravTilSamsvar": "<p>For innhold som oppdateres automatisk, uten å bevege seg, gjelder følgende</p><ul><li>Det er en mekanisme for å pause, stoppe eller skjule innholdet eller styre oppdateringsfre
```suggestion
	"kravTilSamsvar": "<p>For innhold som oppdateres automatisk, uten å bevege seg, og viser samtidig med annet innhold, gjelder følgende</p><ul><li>Det er en mekanisme for å pause, stoppe eller skjule innholdet eller styre oppdateringsfrekvensen og<ul><li>Mekanismen ligger enten på starten av appsiden eller i direkte tilknytning til innholdet eller</li></ul></li><li>Det finnes en dokumentert tastatursnarvei for å pause, stoppe eller skjule innholdet eller styre oppdateringsfrekvensen</li></ul>",
```

2024-03-13 10:40 UTC, ABJORS approved these changes

2024-03-19 08:40 UTC, janBeniaminKwiek approved these changes

2024-03-19 13:21 UTC, merged