app-1.4.2a er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #447
Opened 2024-02-23 08:30 UTC by adilsofficial

2024-03-04 13:45 UTC, janBeniaminKwiek requested changes

2024-03-04 13:45 UTC, janBeniaminKwiek commented on Testreglar/1.4.2/App/app-1.4.2a.json
> +			"ht": "<p>Oppgi URL eller side-ID.</p>",
Da bør vi forandre på standardtekst. URL i apper blir ikke brukt på samme måte og det er misvisende og skrive oppgi URL når dette aldri er tilfellet i en app.

2024-03-12 07:42 UTC, geirsf commented on Testreglar/1.4.2/App/app-1.4.2a.json
> +			"ht": "<p>Oppgi URL eller side-ID.</p>",
```suggestion
			"ht": "<p>Beskriv appsida med få stikkord, eller vel i lista.</p>",
```

2024-03-12 07:55 UTC, geirsf commented on Testreglar/1.4.2/App/app-1.4.2a.json
> +			"ht": "<p>Slik testar du:</p>\n<p>Gjer ein visuell inspeksjon og sjekk om mekanismen har visuell markering.</p>\n<p>Eksempel er</p>\n<ul>\n<li>tekst \"Pause, Stopp, Slå av lyden, Sett filmen på pa
```suggestion
			"ht": "<p>Slik testar du:</p><p>Gjer ein visuell inspeksjon og sjekk om mekanismen har visuell markering.</p><p>Eksempel er</p><ul><li>tekst \"Pause, Stopp, Slå av lyden, Sett filmen på pause…\" </li><li>ikon for volum eller stopp</li></ul>",
```

2024-03-12 07:56 UTC, geirsf commented on Testreglar/1.4.2/App/app-1.4.2a.json
> +			"ht": "<p>Slik testar du:</p>\n<ul>\n<li>Sveip for å nå mekanismen</li>\n<li>Aktiver mekanismen for å skru av eller regulere volumet til null </li>\n<li>Sjekk at lyden blir slått av eller sett til
```suggestion
			"ht": "<p>Slik testar du:</p><ul><li>Sveip for å nå mekanismen</li><li>Aktiver mekanismen for å skru av eller regulere volumet til null </li><li>Sjekk at lyden blir slått av eller sett til null</li></ul>",
```

2024-03-12 11:40 UTC, adilsofficial commented on Testreglar/1.4.2/App/app-1.4.2a.json
> +			"ht": "<p>Oppgi URL eller side-ID.</p>",
Brukt feil standardtekst.

2024-03-19 08:40 UTC, janBeniaminKwiek approved these changes

2024-03-19 13:22 UTC, merged