app-2.2.1a er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #454
Opened 2024-02-28 12:52 UTC by adilsofficial

Vi har ikke valgt å ta med delutfall med Nei fra andre alternativene enn gjeldene alternativ. Mener dere at vi bør ha delutfall med Nei fra tidligere alternativer i siste utfall? @geirsf @janBeniaminKwiek @ABJORS

2024-03-12 12:31 UTC, ABJORS requested changes

2024-03-18 09:12 UTC, adilsofficial commented on Testreglar/2.2.1/App/app-2.2.1a.json
> +			"ht": "<p>Følgjande er unntatt etter ordlyden i kravet:</p>\n<blockquote>\n<ul>\n<li>\n<p>Sanntid: Tidsbegrensningen er en nødvendig del av en hendelse i sanntid (for eksempel en auksjon), og det
Dette er et sitat.

2024-03-18 09:19 UTC, adilsofficial commented on Testreglar/2.2.1/App/app-2.2.1a.json
> +					"type": "gaaTil",
Logikk er riktig.

2024-03-19 08:05 UTC, geirsf requested changes

2024-03-19 08:05 UTC, geirsf commented on Testreglar/2.2.1/App/app-2.2.1a.json
> +						"tekst": "<br>- Mekanismen for å slå av tidsavgrensinga, ligg etter innhaldet med tidsavgrensing."
```suggestion
						"tekst": " Mekanismen for å slå av tidsavgrensinga, ligg etter innhaldet med tidsavgrensing."
```

2024-03-19 08:05 UTC, geirsf commented on Testreglar/2.2.1/App/app-2.2.1a.json
> +						"tekst": "<br>- Mekanismen for å justere varigheit, ligg etter innhaldet med tidsavgrensing."
```suggestion
						"tekst": " Mekanismen for å justere varigheit, ligg etter innhaldet med tidsavgrensing."
```

2024-03-19 08:05 UTC, geirsf commented on Testreglar/2.2.1/App/app-2.2.1a.json
> +						"tekst": "<br>- Mekanismen for å justere varigheita på tidsavgrensinga lar ikkje brukaren justere varigheita på tidsavgrensinga til minst 10 gonger standard varigheit."
```suggestion
						"tekst": " Mekanismen for å justere varigheita på tidsavgrensinga lar ikkje brukaren justere varigheita på tidsavgrensinga til minst 10 gonger standard varigheit."
```

2024-03-19 08:19 UTC, janBeniaminKwiek approved these changes

2024-03-21 09:23 UTC, Sivzilla82 commented on Testreglar/2.2.1/App/app-2.2.1a.json
> +	"kravTilSamsvar": "<p>Det er mulig for brukeren å</p>\r\n<ul>\r\n<li>Slå av tidsavgrensningen, senest 20 sekunder før den skjer, ved å gjøre en enkel handling\r\n<ul>\r\n<li>Mekanismen for å slå av
@geirsf @adilsofficial I og med at det står eller mellom kvar alternativ, så brurde det vera greitt. Når det er sagt har eg no oppdatert innledninga for krav til samsvar slik at det no står: For hver tidsbegrensning som er angitt av innholdet, er det mulig for brukeren å gjøre minst ett av følgende. I tillegg har eg fjerna eller mellom alternativa. Så då håpar eg all tvil er fjerna...

2024-04-02 06:46 UTC, geirsf approved these changes

2024-04-08 10:24 UTC, merged