Endret begrep Accessibility Checker til Accessibility Tree i alle testregler
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #458
Opened 2024-02-29 12:51 UTC by adilsofficial

Endret begrep Accessibility Checker til Accessibility Tree i alle testregler der det er brukt.

2024-03-04 07:11 UTC, geirsf approved these changes

2024-03-06 11:35 UTC, janBeniaminKwiek requested changes
Skal ikke vurdere tilgjengelighet tre, evt annet norsk ord :D

2024-03-12 11:43 UTC, adilsofficial commented
Dette har vi diskutert før og du selv var enig i å bruke engelske begrep. Det står også i begrepsliste. @janBeniaminKwiek

2024-03-12 11:45 UTC, ABJORS approved these changes

2024-03-12 11:47 UTC, adilsofficial commented
Endringer må overføres til testlab før merge til master branch.

2024-03-19 08:20 UTC, janBeniaminKwiek approved these changes

2024-03-19 13:43 UTC, merged