app-1.1.1f er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #462
Opened 2024-03-04 11:35 UTC by adilsofficial

2024-03-12 12:00 UTC, janBeniaminKwiek requested changes

2024-03-12 12:00 UTC, janBeniaminKwiek commented on Testreglar/1.1.1/App/app-1.1.1f.json
> +			"ht": "<p>Slik tester du:</p><ul><li>Aktiver skjermleser<ul><li>iOS: VoiceOver</li><li>Andoird: Talkback</li></ul></li><li>Åpne appsiden på nytt</li><li>Sveip og trykk på videoen eller lydklippet
Hvordan vet vi at det er det tilgjengelige navnet og ikke preview tittel som blir lest opp?

2024-03-13 10:52 UTC, ABJORS approved these changes

2024-03-18 09:58 UTC, adilsofficial commented on Testreglar/1.1.1/App/app-1.1.1f.json
> +			"ht": "<p>Slik tester du:</p><ul><li>Aktiver skjermleser<ul><li>iOS: VoiceOver</li><li>Andoird: Talkback</li></ul></li><li>Åpne appsiden på nytt</li><li>Sveip og trykk på videoen eller lydklippet
Merk: Hvis skjermleser leser opp preview title, så godtar vi det.

2024-03-19 09:28 UTC, geirsf requested changes

2024-03-19 09:28 UTC, geirsf commented on Testreglar/1.1.1/App/app-1.1.1f.json
> +	"kravTilSamsvar": "<p>Ikke-tekstlig innhold som er tidsbaserte medier, har kort tekstalternativ med en beskrivende identifikasjon av det tidsbaserte mediet.</p>",
```suggestion
	"kravTilSamsvar": "<p>Video og lydklipp har et tilgjengelig navn med en beskrivende identifikasjon.</p>",
```

2024-03-19 09:28 UTC, geirsf commented on Testreglar/1.1.1/App/app-1.1.1f.json
> +	"kravTilSamsvar": "<p>Ikke-tekstlig innhold som er tidsbaserte medier, har kort tekstalternativ med en beskrivende identifikasjon av det tidsbaserte mediet.</p>",
I spørsmål 3.2 spør vi om video eller lyd er direktesendt. Dersom vi tolker at kravet til tekstalternativ (1.1.1) bare gjelder for forhåndsinnspilt innhold må det går frem i kravet til samsvar.

2024-04-02 06:58 UTC, geirsf approved these changes

2024-04-22 06:54 UTC, janBeniaminKwiek approved these changes

2024-04-22 08:15 UTC, merged