app-1.2.1b er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #468
Opened 2024-03-06 11:53 UTC by adilsofficial

2024-03-13 12:23 UTC, ABJORS approved these changes

2024-03-13 12:23 UTC, ABJORS commented on Testreglar/1.2.1/App/app-1.2.1b.json
> +			"spm": "Er videoen uten lyd?",
samme som for nett; vurder å snu spørsmålsstilling til: "Har videoen lyd?"

2024-03-19 08:32 UTC, janBeniaminKwiek requested changes

2024-03-19 08:32 UTC, janBeniaminKwiek commented on Testreglar/1.2.1/App/app-1.2.1b.json
> +			"ht": "<p>Slik tester du:</p><ul><li>Gjør en visuell inspeksjon og sjekk om det finnes en play-knapp eller lignende på appsiden eller</li><li>Bruk internt søk på appen om det finnes</li></ul><p><s
Vimeo*  Hvorfor er H264 et søkeparameter?

2024-04-02 08:17 UTC, geirsf approved these changes

2024-04-02 08:17 UTC, geirsf commented on Testreglar/1.2.1/App/app-1.2.1b.json
> +			"ht": "<p>Slik tester du:</p><ul><li>Gjør en visuell inspeksjon og sjekk om det finnes en play-knapp eller lignende på appsiden eller</li><li>Bruk internt søk på appen om det finnes</li></ul><p><s
H264 ligger vell som oftest i en ".mp4" eller ".mkv fil".

2024-04-22 06:55 UTC, janBeniaminKwiek approved these changes

2024-04-22 08:17 UTC, merged