nett-1.4.5a er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #484
Opened 2024-03-14 12:43 UTC by adilsofficial

2024-03-19 08:38 UTC, janBeniaminKwiek requested changes

2024-03-19 08:38 UTC, janBeniaminKwiek commented on Testreglar/1.4.5/Nett/nett-1.4.5a.json
> +	"namn": "Nett-1.4.5a Bilde av tekst er ikkje brukt unødvendig 2023",
Skal de "nye" reglene fortsatt hete 2023?

2024-03-19 08:38 UTC, janBeniaminKwiek commented on Testreglar/1.4.5/Nett/nett-1.4.5a.json
> +			"ht": "<blockquote><em>Bilde av tekst er tekst som presenteres på en måte som ikke er tekstlig (for eksempel som et bilde), for å oppnå en spesiell visuell effekt.</em></blockquote><blockquote><em
Ser vi ikke har tatt med Bilde av tekst i SoMe. Er det fordi denne regelen er blitt laget før diskusjonen 18.03?

2024-04-08 12:23 UTC, geirsf requested changes

2024-04-08 12:23 UTC, geirsf commented on Testreglar/1.4.5/Nett/nett-1.4.5a.json
> +	"kravTilSamsvar": "<ul><li>Bilde av tekst kan visuelt tilpasses brukerens krav<ul><li>skrifttype, størrelse, farge og bakgrunn kan endres</li></ul></li><li>Bilde av tekst er brukt fordi en bestemt p
```suggestion
	"kravTilSamsvar": "<p>Bilde av tekst er bare brukt dersom:</p><ul><li>det kan visuelt tilpasses brukerens krav<ul><li>skrifttype, størrelse, farge og bakgrunn kan endres</li></ul></li><li>en bestemt presentasjon av innholdet er avgjørende</li></ul>",
```

2024-04-08 12:23 UTC, geirsf commented on Testreglar/1.4.5/Nett/nett-1.4.5a.json
> +	"kravTilSamsvar": "<ul><li>Bilde av tekst kan visuelt tilpasses brukerens krav<ul><li>skrifttype, størrelse, farge og bakgrunn kan endres</li></ul></li><li>Bilde av tekst er brukt fordi en bestemt p
Få tydeligere frem at det er bruken av bilde av tekst som er sentral for kravet, dagens krav til samsvar har bare info om unntakene.

2024-04-08 12:23 UTC, geirsf commented on Testreglar/1.4.5/Nett/nett-1.4.5a.json
> +			"ht": "<p>Eksempel på situasjonar der bruk av bilde av tekst er nødvendig:</p><ul><li>Det ikkje er mogleg å formatere teksten for å oppnå same effekt.</li><li>Det ikkje er mogleg å presentere effe
Det er ikkje **teknisk** er mogleg å formatere teksten for å oppnå same effekt. -> Dersom det er det som er tenkt vurdert.

2024-04-10 09:43 UTC, ABJORS approved these changes

2024-04-15 10:26 UTC, adilsofficial commented on Testreglar/1.4.5/Nett/nett-1.4.5a.json
> +			"ht": "<blockquote><em>Bilde av tekst er tekst som presenteres på en måte som ikke er tekstlig (for eksempel som et bilde), for å oppnå en spesiell visuell effekt.</em></blockquote><blockquote><em
Vi oppdaterer testregel med nye eksempler inkl. SoMe og laster opp testregel på nytt.

2024-04-15 10:39 UTC, adilsofficial commented on Testreglar/1.4.5/Nett/nett-1.4.5a.json
> +			"ht": "<p>Eksempel på situasjonar der bruk av bilde av tekst er nødvendig:</p><ul><li>Det ikkje er mogleg å formatere teksten for å oppnå same effekt.</li><li>Det ikkje er mogleg å presentere effe
Legg til noen eksempler for forståartikkelen.

2024-04-22 06:56 UTC, janBeniaminKwiek approved these changes

2024-04-22 08:18 UTC, merged