app-1.4.5a er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #485
Opened 2024-03-14 12:46 UTC by adilsofficial

2024-04-02 07:10 UTC, janBeniaminKwiek requested changes

2024-04-02 07:10 UTC, janBeniaminKwiek commented on Testreglar/1.4.5/App/app-1.4.5a.json
> +			"spm": "Er bildet av tekst, faktisk eit bilde?",
Kan ikke vi sjekke dette i 2.2? Føles unødvendig ut å sjekke om bilde av tekst faktisk er et bilde av tekst når du har svart på at det er bilde av tekst.

2024-04-02 07:10 UTC, janBeniaminKwiek commented on Testreglar/1.4.5/App/app-1.4.5a.json
> +			"spm": "Går informasjon/funksjonalitet i presentasjonen tapt, viss bilde av tekst blir koda som tekst?",
Skal vi ha eksempel her? eller legger vi det til forståartikkelen?

2024-04-08 12:26 UTC, geirsf requested changes

2024-04-08 12:26 UTC, geirsf commented on Testreglar/1.4.5/App/app-1.4.5a.json
> +	"kravTilSamsvar": "<ul><li>Bilde av tekst kan visuelt tilpasses brukerens krav<ul><li>skrifttype, størrelse, farge og bakgrunn kan endres</li></ul></li><li>Bilde av tekst er brukt fordi en bestemt p
Samma kommentar som for Nett. Få tydeligere frem at det er bruken av bilde av tekst som er sentral for kravet, dagens krav til samsvar har bare info om unntakene.

2024-04-08 12:26 UTC, geirsf commented on Testreglar/1.4.5/App/app-1.4.5a.json
> +			"ht": "<p>Eksempel på situasjonar der bruk av bilde av tekst er nødvendig:</p><ul><li>Det ikkje er mogleg å formatere teksten for å oppnå same effekt.</li><li>Det ikkje er mogleg å presentere effe
Det er ikkje **teknisk** er mogleg å formatere teksten for å oppnå same effekt. -> Dersom det er det som er tenkt vurdert.

2024-04-10 09:49 UTC, ABJORS approved these changes

2024-04-15 10:39 UTC, adilsofficial commented on Testreglar/1.4.5/App/app-1.4.5a.json
> +			"spm": "Er bildet av tekst, faktisk eit bilde?",
Steg 2.2 er oppdatert og 2.4 er fjernet.

2024-04-15 10:39 UTC, adilsofficial commented on Testreglar/1.4.5/App/app-1.4.5a.json
> +			"spm": "Går informasjon/funksjonalitet i presentasjonen tapt, viss bilde av tekst blir koda som tekst?",
Ja! Vi kan godt lage noen eksempler her.

2024-04-16 13:23 UTC, geirsf approved these changes

2024-04-22 06:56 UTC, janBeniaminKwiek approved these changes

2024-04-22 08:18 UTC, merged