nett-2.3.1a er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #494
Opened 2024-03-25 12:22 UTC by adilsofficial

2024-04-02 07:27 UTC, janBeniaminKwiek requested changes

2024-04-02 07:27 UTC, janBeniaminKwiek commented on Testreglar/2.3.1/Nett/nett-2.3.1a.json
> +			"spm": "Sett oppløysinga på skjermen du brukar til 1024*768.",
Skal vi ikke bruke samme oppløsning som ved 1.4.4. Det er nye og oppdaterte tall som er bedre for 2024.

2024-04-10 11:39 UTC, ABJORS commented on Testreglar/2.3.1/Nett/nett-2.3.1a.json
> +			"ht": "<p>Beskriv innhaldet som glimtar, slik at det er mogleg å identifisere det i ettertid.</p><p>Viss det gjeld fleire innhald, registrerer du eit og eit.</p>",
Vurder å erstatte "Viss det gjeld fleire innhald,..." med "Viss det gjeld fleire element"

2024-04-10 13:14 UTC, geirsf approved these changes

2024-04-15 10:45 UTC, ABJORS approved these changes

2024-04-22 06:57 UTC, janBeniaminKwiek approved these changes

2024-04-22 08:19 UTC, merged