app-2.3.1a er klar for ks
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #495
Opened 2024-03-25 12:25 UTC by adilsofficial

2024-04-02 07:29 UTC, janBeniaminKwiek requested changes

2024-04-02 07:29 UTC, janBeniaminKwiek commented on Testreglar/2.3.1/App/app-2.3.1a.json
> +			"ht": "<p>Slik testar du:</p><p>Ta skjermbilde av appsida og send det til PCen.</p><ul><li>Bruk Snagit eller Windows Paint for å måle størrelsen<br><ul><li>Vel alternativ Merket område &gt; Rektan
Fjern paint som alternativ. Eventuelt bare gi en generell fremgangsmåte som er uavhengig av teknologien brukt.

2024-04-10 11:50 UTC, ABJORS requested changes

2024-04-10 11:50 UTC, ABJORS commented on Testreglar/2.3.1/App/app-2.3.1a.json
> +			"ht": "<p>Beskriv innhaldet som glimtar, slik at det er mogleg å identifisere det i ettertid.</p><p>Viss det gjeld fleire innhald, registrerer du eit og eit.</p>",
vurder omskriving, ref. kommentar nett-2.3.1

2024-04-10 11:50 UTC, ABJORS commented on Testreglar/2.3.1/App/app-2.3.1a.json
> +			"label": "Innhald som glimtar/glimptar:",
vurder omskriving, ref. kommentar nett-2.3.1

2024-04-10 13:16 UTC, geirsf commented on Testreglar/2.3.1/App/app-2.3.1a.json
> +			"label": "Innhald som glimtar/glimptar:",
glimptar?

2024-04-10 13:41 UTC, geirsf approved these changes

2024-04-15 10:47 UTC, adilsofficial commented on Testreglar/2.3.1/App/app-2.3.1a.json
> +			"ht": "<p>Slik testar du:</p><p>Ta skjermbilde av appsida og send det til PCen.</p><ul><li>Bruk Snagit eller Windows Paint for å måle størrelsen<br><ul><li>Vel alternativ Merket område &gt; Rektan
Lagt inn begrept "liknande" slik at en kan velge et verktøy en vil.

2024-04-15 10:48 UTC, ABJORS approved these changes

2024-04-22 06:57 UTC, janBeniaminKwiek approved these changes

2024-04-22 08:19 UTC, merged