Testlab 2.0 støtte - Rekkefølge på steg i ruting
TilsynForUniversellUtforming/testreglar-wcag-2.x pull request #517
Opened 2024-04-19 10:56 UTC by adilsofficial

Oppdatert ruting i testregler listet i sak #504.
Vennligst test grundig.

2024-04-22 11:20 UTC, geirsf requested changes

2024-04-24 07:54 UTC, adilsofficial commented on Testreglar/1.1.1/Nett/1.1.1d.json
>  		},
Kan legge til denne rutingen under steg 3.14 samme som nett-1.1.1d. Hva synes du om det?
			"3": {
				"type": "lik",
				"sjekk": "3.14",
				"verdi": "Ja",
				"handling": {
					"type": "gaaTil",
					"steg": "3.15",
					"delutfall": {
						"nr": 2,
						"fasit": "Ja",
						"tekst": "CAPTCHA i form av ei logisk oppgåve, er koda som tekst."
					}
				}
			}

2024-04-26 11:32 UTC, janBeniaminKwiek approved these changes

2024-04-26 11:45 UTC, ABJORS approved these changes

2024-04-29 08:02 UTC, merged